k8ssandra/k8ssandra

docs/content/en/_index.md

Hi all! I'm a teammate of @toffer. This is a fix for correcting his name and title.

Fix Tom's name and title

---

charts/backup/Chart.yaml
charts/k8ssandra-cluster/Chart.yaml
charts/k8ssandra-cluster/templates/traefik.ingressroutes.yaml
charts/k8ssandra/Chart.yaml
charts/restore/Chart.yaml

Added missing `labels` stanza to traefik IngressRouteTCP CR

added missing labels stanza

---

charts/backup/Chart.yaml
charts/k8ssandra-cluster/Chart.yaml
charts/k8ssandra-cluster/templates/medusa-operator/deployment.yaml
charts/k8ssandra/Chart.yaml
charts/restore/Chart.yaml

Fixes #102 
Note that https://github.com/k8ssandra/medusa-operator/pull/5 needs to be merged as well.

[GH 102] update medusa-operator image

---

charts/k8ssandra-cluster/templates/reaper.yaml
charts/k8ssandra/crds/reaper/reaper.yaml

This is for issue #45 , requires updated reaper-operator to function correctly.

Modify reaper configuration to use CassandraDatacenter

---

charts/backup/Chart.yaml
charts/k8ssandra-cluster/Chart.yaml
charts/k8ssandra-cluster/templates/reaper-operator/deployment.yaml
charts/k8ssandra-cluster/templates/reaper.yaml
charts/k8ssandra-cluster/values.yaml
charts/k8ssandra/Chart.yaml
charts/k8ssandra/crds/reaper/reaper.yaml
charts/restore/Chart.yaml

Fixes #95, requires update of reaper-operator.

Allow setting autoscheduling to enabled in the values

---

docs/content/en/docs/topics/ingress/traefik/k3d-deployment/_index.md

Updated link to the traefik example yaml.

Update doc for k3d _index.md

---

.gitattributes

Classify so the .go files are picked up for language classification.

Initial attributes for language classification

---

.github/workflows/main-docs.yaml
docs/config.toml
docs/content/en/docs/faqs/_index.md
docs/content/en/docs/topics/_index.md
docs/content/en/docs/topics/accessing-services/_index.md
docs/content/en/docs/topics/accessing-services/cassandra/_index.md
docs/content/en/docs/topics/accessing-services/monitoring/_index.md
docs/content/en/docs/topics/accessing-services/repair/_index.md
docs/content/en/docs/topics/accessing-services/stargate/_index.md
docs/content/en/docs/topics/ingress/_index.md
docs/content/en/docs/topics/ingress/traefik/_index.md
docs/content/en/docs/topics/ingress/traefik/k3d-deployment/_index.md
docs/content/en/docs/topics/ingress/traefik/kind-deployment/_index.md
docs/content/en/docs/topics/ingress/traefik/monitoring/_index.md
docs/content/en/docs/topics/ingress/traefik/repair/_index.md
docs/content/en/docs/topics/provision-a-cluster/_index.md
docs/content/en/docs/topics/restore-a-backup/_index.md
docs/layouts/_default/sitemap.xml

Added ping for sitemap to docs push

Added layout for sitemap.xml

---

docs/content/en/docs/topics/provision-a-cluster/_index.md

Related to an [issue](https://github.com/k8ssandra/k8ssandra/issues/89) where previously set values are not preserved for `helm update`.

Include use of --reuse-values flag for helm update

---

charts/backup/Chart.yaml
charts/k8ssandra-cluster/Chart.yaml
charts/k8ssandra/Chart.yaml
charts/restore/Chart.yaml
scripts/helm-version.py

```
michael@nina ~/p/g/d/k8ssandra (update_chart_version)> scripts/helm-version.py --incr patch
Updated /home/michael/projects/git/datastax/k8ssandra/charts/backup/Chart.yaml to 0.17.1
Updated /home/michael/projects/git/datastax/k8ssandra/charts/restore/Chart.yaml to 0.17.1
Updated /home/michael/projects/git/datastax/k8ssandra/charts/k8ssandra/Chart.yaml to 0.17.1
Updated /home/michael/projects/git/datastax/k8ssandra/charts/k8ssandra-cluster/Chart.yaml to 0.17.1
michael@nina ~/p/g/d/k8ssandra (update_chart_version)>
```

Bump chart versions to 0.17.1, add a script

---

charts/backup/Chart.yaml
charts/k8ssandra-cluster/Chart.yaml
charts/k8ssandra-cluster/templates/reaper.yaml
charts/k8ssandra/Chart.yaml
charts/restore/Chart.yaml
scripts/helm-version.py

Update Reaper to 2.1.3

---

charts/backup/Chart.yaml
charts/k8ssandra-cluster/Chart.yaml
charts/k8ssandra-cluster/templates/cassdc.yaml
charts/k8ssandra-cluster/templates/prometheus/service_monitor.yaml
charts/k8ssandra-cluster/templates/reaper.yaml
charts/k8ssandra-cluster/templates/stargate/stargate.yaml
charts/k8ssandra-cluster/templates/traefik.ingressroutes.yaml
charts/k8ssandra-cluster/values.yaml
charts/k8ssandra/Chart.yaml
charts/restore/Chart.yaml
tests/unit/template_cassdc_test.go
tests/unit/template_reaper_test.go

This PR removes unused properties and moves properties under the top-level `k8ssandra` property.

Property cleanup

---

charts/backup/Chart.yaml
charts/k8ssandra-cluster/Chart.yaml
charts/k8ssandra-cluster/templates/cassdc.yaml
charts/k8ssandra-cluster/values.yaml
charts/k8ssandra/Chart.yaml
charts/restore/Chart.yaml
tests/unit/template_cassdc_test.go

Supported values include:
* 3.11.7
* 3.11.8
* 3.11.9

add support for setting C* version

---

charts/backup/Chart.yaml
charts/k8ssandra-cluster/Chart.yaml
charts/k8ssandra-cluster/templates/cassdc.yaml
charts/k8ssandra/Chart.yaml
charts/restore/Chart.yaml
tests/unit/template_cassdc_test.go

do not run as C* user

---

scripts/delete-crds.sh

Just a small helper script to remove CRDs.

add script to delete CRDS

---

charts/backup/Chart.yaml
charts/k8ssandra/Chart.yaml
charts/k8ssandra/charts/cass-operator/Chart.yaml
charts/k8ssandra/charts/cass-operator/crds/customresourcedefinition.yaml
charts/k8ssandra/charts/cass-operator/templates/clusterrole.yaml
charts/k8ssandra/charts/cass-operator/templates/clusterrolebinding.yaml
charts/k8ssandra/charts/cass-operator/templates/deployment.yaml
charts/k8ssandra/charts/cass-operator/templates/registry-secret.yaml
charts/k8ssandra/charts/cass-operator/templates/role.yaml
charts/k8ssandra/charts/cass-operator/templates/rolebinding.yaml
charts/k8ssandra/charts/cass-operator/templates/validatingwebhookconfiguration.yaml
charts/k8ssandra/charts/cass-operator/templates/webhook-cr.yaml
charts/k8ssandra/charts/cass-operator/templates/webhook-service.yaml
charts/k8ssandra/charts/cass-operator/values.yaml
charts/k8ssandra/templates/cassdc.yaml
charts/k8ssandra/values.yaml
charts/restore/Chart.yaml
tests/unit/template_cassdc_test.go

Fixes #112
Making this a draft PR until we are able to switch over to an official datastax/cass-operator image. We are just waiting on images to be pushed.

cass-operator upgrade

---

docs/content/en/docs/getting-started/_index.md

This was mentioned in slack conversation recently as being confusing.

Updating text related to the chart consolidation

---

pkg/cleaner/cleaner.go
pkg/cleaner/cleaner_test.go

@jsanda This is for testing the docker image process

Return error code if removal failed

---

pkg/cleaner/cleaner_test.go

Another attempt for the automated image build

---

charts/k8ssandra/templates/cassandra/cassdc.yaml
charts/k8ssandra/templates/medusa-config.yaml
charts/k8ssandra/values.yaml

Fixes #190 
The updated image also includes the changes needed for #154. Specifically it includes https://github.com/thelastpickle/cassandra-medusa/pull/263.

update medusa image

---

charts/k8ssandra/Chart.yaml
charts/k8ssandra/crds/medusa/backup.yaml
charts/k8ssandra/templates/medusa-operator/deployment.yaml
charts/restore/Chart.yaml
charts/restore/templates/restore.yaml
charts/restore/values.yaml

Fixes #229 and #226
This PR has the following changes:
* Updates medusa-operator image
* Update CassandraBackup CRD
* Update CassandraRestore CRD
* Updates restore template with latest changes in medusa-operator

Upgrade medusa-operator

---

charts/k8ssandra/Chart.yaml
charts/k8ssandra/templates/cassandra/cassdc.yaml
charts/k8ssandra/values.yaml
tests/unit/template_cassdc_test.go
tests/unit/testdata/racks-affinity-values.yaml
tests/unit/testdata/racks-no-affinity-values.yaml

Fixes #54.
#230 needs to be merged first.
The only thing I have left to do is update the comments in `k8ssandra/values.yaml` and bump the chart version.

Add rack support

---

.github/pull_request_template.md
CONTRIBUTING.md

* Adds this pull request template
* Adds a CONTRIBUTING.md file which references k8ssandra.io
N/A
**Checklist**

Adding CONTRIBUTING.md file and pull request template

---

charts/k8ssandra/Chart.yaml
charts/k8ssandra/templates/cassandra/cassdc.yaml
charts/k8ssandra/values.yaml

…ewhere
Updates the default Medusa image so that it includes the changes from https://github.com/thelastpickle/cassandra-medusa/pull/265.
Fixes #256 
**Checklist**

Update Medusa image and refactor properties

---

charts/k8ssandra/Chart.yaml
charts/k8ssandra/templates/reaper/reaper.yaml
charts/k8ssandra/values.yaml

* Makes reaper image configurable
* Adds docs for reaper properties in values.yaml
Fixes #270 
**Checklist**

Make the reaper image configurable

---

charts/k8ssandra/Chart.yaml
charts/k8ssandra/templates/_helpers.tpl
charts/k8ssandra/templates/cassandra/cassdc.yaml
charts/k8ssandra/templates/cassandra/superuser-secret.yaml
charts/k8ssandra/templates/medusa/medusa-user-secret.yaml
charts/k8ssandra/templates/prometheus/service_monitor.yaml
charts/k8ssandra/templates/reaper/reaper-user-secret.yaml
charts/k8ssandra/templates/reaper/reaper.yaml
charts/k8ssandra/templates/stargate/stargate-user-secret.yaml
charts/k8ssandra/templates/stargate/stargate.yaml
charts/k8ssandra/templates/traefik.ingressroutes.yaml
charts/k8ssandra/values.yaml
tests/unit/template_cassdc_test.go

Defaults clusterName to Release.Name when not specified.
Fixes # 299
**Checklist**

ClusterName defaults to Release.Name

---

charts/k8ssandra/Chart.yaml
charts/k8ssandra/templates/cassandra/cassdc.yaml
charts/k8ssandra/values.yaml
tests/unit/template_cassdc_test.go

Adds support for Cassandra 3.11.10
Fixes #308

add support for C* 3.11.10 and make it the default version

---

docs/content/en/docs/topics/ingress/traefik/minikube-deployment/_index.md

Fix link to the sample yaml

---

docs/content/en/docs/topics/dev-tools/_index.md

Adds developer-level documentation for existing `scripts` included in the `k8ssandra` project.
Fixes #285 
**Checklist**

Developer documentation for existing scripts

---

charts/k8ssandra/Chart.yaml
charts/k8ssandra/templates/cassandra/ingress.yaml
charts/k8ssandra/templates/stargate/cassandra-ingress.yaml
tests/unit/template_cassandra_ingress_test.go
tests/unit/template_stargate_cassandra_ingress_test.go
tests/unit/template_stargate_test.go
tests/unit/tests_suite_test.go
tests/unit/utils/traefik/tcpRoutes.go

My previous fix (#294) was trampled in #333. Adding unit tests for it this time, fixing a bug in a test utility function, and doing a bit of minor test cleanup.
Fixes #293
**Checklist**

Re-fixing #293 for both C* ingress and Stargate C* ingress. 

---

charts/k8ssandra/Chart.yaml
charts/k8ssandra/templates/stargate/stargate.yaml
tests/unit/template_stargate_test.go

Upgrades to the latest version of Stargate
Fixes #254
**Checklist**

upgrading Stargate to 1.0.7 (latest)

---

docs/content/en/docs/topics/accessing-services/stargate/_index.md

... user sent me Slack msg that the URLs with placeholders were broken.
**Checklist**

Help users with localhost:port example URLs

---

charts/k8ssandra/Chart.yaml
docs/content/en/docs/faqs/_index.md

Updates the list of versions in our docs
Fixes #358
**Checklist**

#358: updating versions in docs

---

docs/content/en/docs/topics/ingress/traefik/k3d-deployment/_index.md

previously went from 3 to 5
**Checklist**

Fix manual list numbering

---

docs/content/en/docs/topics/restore-a-backup/backup-restore-values.yaml

Add S3 region example

---

docs/content/en/docs/topics/provision-a-cluster/_index.md

Fix typo reqiuirements s/b requirements

---

docs/content/en/docs/topics/restore-a-backup/_index.md

Old: /docs/topics/accessing-services/repair/.  New: /docs/topics/repair/
**Checklist**

Fix ref L328

---

docs/content/en/docs/faqs/_index.md

Clean up FAQs

---

charts/k8ssandra/values.yaml

Removes stargate.clusterVersion from values.yaml

Remove stargate.clusterVersion from values.yaml

---

docs/content/en/docs/topics/restore-a-backup/test_data.cql

for medusa_test cqlsh for consistency with Quick start
**Checklist**

Use same sample data

---

docs/content/en/docs/topics/restore-a-backup/_index.md

and same cqlsh sample rows for medusa_test as done in Quick start.
**Checklist**

Use alerts for notes

---

charts/k8ssandra/Chart.yaml
charts/k8ssandra/templates/cassandra/cassdc.yaml
tests/unit/template_cassdc_test.go
tests/unit/testdata/config-override-values.yaml

add support for configOverride property

---

charts/k8ssandra/values.yaml

Upgrade Reaper and Medusa to their latest releases.
Fixes #422
**Checklist**
Tests have run successfully locally and are currently running [in CircleCI](https://app.circleci.com/pipelines/github/adejanovski/k8ssandra/30/workflows/902437a1-e519-4782-b6eb-edda4edbbd3a).
These integration tests will possibly be added to `main` post 1.0.

Upgrade to Reaper 2.2.1 and Medusa 0.9.0

---

docs/content/en/docs/faqs/_index.md

Update docs to reference the newer versions of medusa and reaper we've now included.
**Checklist**

Update the versions included for reaper and medusa.

---

charts/k8ssandra/Chart.yaml

Upgrade helm charts version.
**Checklist**

Upgrade Helm chart version for Reaper/Medusa upgrade

---

docs/content/en/docs/topics/provision-a-cluster/_index.md

e.g. using --set k8ssandra.size=<value> and related edits
**Checklist**

Fix scale up/down examples

---

docs/content/en/docs/topics/restore-a-backup/_index.md

Medusa cleanup

---

charts/k8ssandra/Chart.yaml
charts/k8ssandra/templates/_helpers.tpl
charts/k8ssandra/templates/reaper/reaper.yaml
tests/unit/template_reaper_test.go

Selects correct reaper JMX secret name as well as Cassandra secret name
Fixes #433 
**Checklist**

Fix reaper usersecret

---

docs/content/en/docs/topics/repair/_index.md

Update scheduling info for Reaper

---

docs/content/en/docs/faqs/_index.md

Minor edits

---

docs/content/en/_index.md

Updates the CLI installation video on the home screen to use the consolidated chart install.
* Video is available here:  https://asciinema.org/a/392352
Fixes #310 
**Checklist**

Recorded a new video of the quick cli install for the home page

---

docs/content/en/docs/topics/restore-a-backup/_index.md

Format cleanup and minor edits

---

docs/content/en/docs/third-party/_index.md

Update intro text

---

docs/content/en/docs/architecture/monitoring/_index.md
docs/content/en/docs/architecture/repairs/_index.md
docs/content/en/docs/faqs/_index.md
docs/content/en/docs/getting-started/site-engineer/_index.md
docs/content/en/docs/topics/ingress/traefik/repair/_index.md
docs/content/en/docs/topics/repair/_index.md
docs/content/en/docs/topics/restore-a-backup/_index.md

**What this PR does**: Fixes dangling Medusa/Reaper mentions. Most of them.
Fixes #NA
**Checklist**

More product name wrangling for Medusa and Reaper.

---

.github/pull_request_template.md

Added field for indicating if the CHANGELOG was updated.
**Checklist**

Added field for indicating if the CHANGELOG was updated.

---

docs/content/en/blog/articles/why-k8ssandra/index.md

Update Why K8ssandra blog

---

docs/content/en/blog/articles/release-1.0/index.md

Minor updates to 1.0 release blog.
**Checklist**

1.0 Blog Post Updates

---

docs/content/en/docs/topics/repair/_index.md

adding with this commit - will close PR 369 which has merge conflicts
**Checklist**

autoschedule repair info

---

docs/content/en/blog/articles/release-1.0/index.md

**What this PR does**: Adds missing components from 1.0 blog post
Fixes #458 
**Checklist**

Added missing components

---

scripts/helm-version.py

Improve scripts/helm-version.py with new functionality ``--dep`` to update the dependency in k8ssandra Chart also.
```
➜  k8ssandra git:(script_dep_update) ✗ scripts/helm-version.py --incr patch --chart medusa-operator      
Updated /Users/michael.burman/projects/datastax/k8ssandra/charts/medusa-operator/Chart.yaml to 0.28.5
➜  k8ssandra git:(script_dep_update) ✗ scripts/helm-version.py --incr patch --chart medusa-operator --dep
Updated /Users/michael.burman/projects/datastax/k8ssandra/charts/medusa-operator/Chart.yaml to 0.28.6
Updated dependency medusa-operator to 0.28.6
Updated /Users/michael.burman/projects/datastax/k8ssandra/charts/k8ssandra/Chart.yaml to 1.0.1
➜  k8ssandra git:(script_dep_update) ✗
```
**Checklist**

Parameter --dep allows to update the dependency in k8ssandra Chart.yaml

---

docs/content/en/docs/topics/restore-a-backup/_index.md

Minor edit

---

docs/content/en/docs/topics/restore-a-backup/_index.md
docs/content/en/docs/topics/restore-a-backup/backup-restore-values.yaml

Update chart properties for backup/restore with Medusa

---

charts/k8ssandra/Chart.yaml
charts/k8ssandra/templates/cassandra/cassdc.yaml
charts/k8ssandra/templates/medusa/medusa-config.yaml
charts/k8ssandra/values.yaml
tests/unit/template_cassdc_test.go
tests/unit/template_medusa_config_test.go
tests/unit/utils/kubeapi/volumes.go

Fix local storage configuration

---

docs/content/en/docs/topics/ingress/_index.md
docs/content/en/docs/topics/ingress/traefik/monitoring/_index.md
docs/content/en/docs/topics/ingress/traefik/repair/_index.md
docs/content/en/docs/topics/monitoring/_index.md
docs/content/en/docs/topics/repair/_index.md

Tips to consider port forward as alt to ingress

---

docs/content/en/docs/faqs/_index.md

Updates the FAQ about installing multiple releases of the k8ssandra chart.
**Checklist**

fix FAQ about installing multiple releases

---

docs/content/en/docs/topics/provision-a-cluster/_index.md

Update size up/down example

---

.github/workflows/release-next.yaml
CHANGELOG.md

Checks out repo before attempting to run scripts contained within
**Checklist**

Added checkout before running build script

---

docs/content/en/docs/topics/restore-a-backup/_index.md

Clarify use of backup test example for the restore

---

docs/content/en/docs/topics/ingress/traefik/_index.md

Issue number 207, related to PR 200
**Checklist**

Add prod warning about Traefik examples

---

CHANGELOG.md
charts/k8ssandra/Chart.yaml
charts/k8ssandra/values.yaml
docs/content/en/docs/faqs/_index.md

Upgrade Reaper to 2.2.2 and Medusa to 0.9.0

---

docs/content/en/blog/articles/dev-config/index.md

**What this PR does**: Update linkTitle in K8ssandra development blogpost
**Checklist**

Update linkTitle in K8ssandra development blogpost

---

CHANGELOG.md
README.md
dev-quick-start.md

Introduces developer level quick start documentation for k8ssandra developers to reference.
Fixes #239 
**Checklist**

239 dev docs

---

.github/CODEOWNERS

**What this PR does**: Adds a basic CODEOWNERS file to facilitate automatic assignment of PR reviewers
**Checklist**

Adding initial CODEOWNERS file

---

contrib/upgrade-cass-operator.md

This PR adds a doc for the steps involved with upgrading cas-operator. I am keeping it outside of the main docs because I am not sure it belongs there. Furthermore, as we build out dev docs for medusa-operator and reaper-operator, this will need to be updated to link to those docs.
Fixes #462
**Checklist**

Doc for upgrading cass-operator

---

docs/content/en/docs/getting-started/_index.md

Fix indentation for Grafana in getting-started docs.
Fixes #584
**Checklist**

Docs Fix - getting-started Grafana indentation

---

CHANGELOG.md
charts/cass-operator/Chart.yaml
charts/cass-operator/templates/deployment.yaml
charts/cass-operator/templates/webhook-secret.yaml
charts/k8ssandra/Chart.yaml

Create webhook secret to ensure cass-operator deployment isn't blocked

---

CHANGELOG.md
charts/k8ssandra/Chart.yaml
charts/k8ssandra/templates/cassandra/cassdc.yaml
charts/k8ssandra/values.yaml
tests/unit/template_cassdc_test.go

[#576] add option to disable server-system-logger container

---

docs/content/en/blog/articles/why-k8ssandra/index.md

Optimizing Developer Productivity, Cost, and Performance:
This is why K8ssandra also includes [K8ssandra also includes Stargate](/docs/topics/stargate) results in duplication of "K8ssandra also includes" - removed the first one and left the link text intact.
his is why K8ssandra also includes [K8ssandra also includes Stargate](/docs/topics/stargate) results in duplication of "K8ssandra also includes" - removed the first one and left the link text intact.
No issue # - input via Slack
**Checklist**
- [x ] Changes manually tested
- [x ] Automated Tests added/updated
- [x ] Documentation added/updated

Remove duplicate text

---

CHANGELOG.md
docs/content/en/docs/topics/restore-a-backup/backup-restore-values.yaml

fix indentation in example backup-restore-values.yaml

---

docs/content/en/blog/articles/why-k8ssandra/index.md

Removing a double text entry
**Checklist**

Fixing text

---

docs/content/en/blog/articles/k8ssandra-first-touch/index.md

New blog post featuring first touch video
**Checklist**

adding blog post for first touch video

---

docs/content/en/blog/articles/k8ssandra-first-touch/index.md

fix cut and paste error from previous blog post
**Checklist**

Update blog post description

---

docs/content/en/docs/third-party/_index.md

**What this PR does**: Adds the license to k8ssandra.io
Fixes #574
**Checklist**

Note K8ssandra sw is licensed under Apache-2.0

---

docs/content/en/docs/topics/monitoring/_index.md

Correct link to SRE topic on port-forwarding

---

.github/workflows/integration-tests.yaml

Don't run integration tests on docs changes

---

docs/content/en/docs/topics/provision-a-cluster/_index.md

Improve scaling info adding removing nodes and underlying operations

---

docs/content/en/docs/topics/migration/_index.md

Add topic on migrating existing Cassandra to K8ssandra

---

docs/config.toml
docs/content/en/_index.md
docs/content/en/docs/_index.md
docs/content/en/docs/architecture/backups/_index.md
docs/content/en/docs/architecture/cassandra/_index.md
docs/content/en/docs/architecture/monitoring/_index.md
docs/content/en/docs/architecture/repairs/_index.md
docs/content/en/docs/architecture/stargate/_index.md
docs/content/en/docs/getting-started/_index.md
docs/content/en/docs/getting-started/developer/_index.md
docs/content/en/docs/getting-started/site-engineer/_index.md
docs/content/en/docs/topics/_index.md
docs/content/en/docs/topics/ingress/_index.md
docs/content/en/docs/topics/ingress/traefik/_index.md
docs/content/en/docs/topics/ingress/traefik/k3d-deployment/_index.md
docs/content/en/docs/topics/ingress/traefik/kind-deployment/_index.md
docs/content/en/docs/topics/ingress/traefik/minikube-deployment/_index.md
docs/content/en/docs/topics/ingress/traefik/monitoring/_index.md
docs/content/en/docs/topics/ingress/traefik/repair/_index.md
docs/content/en/docs/topics/monitoring/_index.md
docs/content/en/docs/topics/provision-a-cluster/_index.md
docs/content/en/docs/topics/repair/_index.md
docs/content/en/docs/topics/restore-a-backup/_index.md
docs/content/en/docs/topics/stargate/_index.md

Improvements to documentation site page titles and descriptions to improve search results.
**Checklist**

Search improvement

---

README.md

Fixes broken link @jeffreyscarpenter found when reviewing another artifact.
**Checklist**

Fix for broken dev quick-start link

---

CHANGELOG.md
charts/restore/Chart.yaml
charts/restore/values.yaml

shutdown cluster by default

---

.github/workflows/integration-tests.yaml

In order to allow triggering the release stable workflow based on the integration tests execution, it seems like it needs to be named properly and exist in the default branch of the project.
**Checklist**

Name the IT workflow to allow triggering downstream GHA workflows

---

charts/k8ssandra/values.yaml

bump cleaner image version

---

docs/config.toml

Update google analytics id

---

.github/workflows/integration-tests.yaml

Also include the gha workflow changes as trigger for ITs.
Run the integration tests workflow on pushes to release branches and include the gha workflow files changes as enablers.
Fixes #632
**Checklist**

Run integration tests on pushes to release branches

---

CHANGELOG.md
charts/k8ssandra/values.yaml
tests/unit/template_cassdc_test.go

Updates the Management API image locations.
Fixes #637
**Checklist**

Update Management API image locations

---

CHANGELOG-1.2.md

Start new changelog for 1.2 work

Create changelog for 1.2

---

docs/content/en/blog/news/cloud-native-cassandra.md
docs/content/en/blog/news/dba_to_sre.md
docs/content/en/blog/news/k8ssandra-launch.md
docs/content/en/blog/news/leading_with_code.md
docs/content/en/blog/news/production-ready-platform.md
docs/content/en/blog/news/unboxing_k8ssandra.md

Adding relevant K8ssandra news coverage to the blog.
**Checklist**

News items

---

docs/content/en/docs/faqs/_index.md
docs/content/en/docs/getting-started/_index.md
docs/content/en/docs/release-notes/_index.md
docs/content/en/docs/topics/provision-a-cluster/_index.md
docs/content/en/docs/topics/repair/_index.md

Fix leftnav sequence of topics and update CHANGELOG link

---

docs/content/en/docs/topics/stargate/_index.md

Format localhost url examples as plain text to avoid link warnings

---

docs/content/en/docs/topics/ingress/_index.md
docs/content/en/docs/topics/ingress/traefik/monitoring/_index.md
docs/content/en/docs/topics/ingress/traefik/repair/_index.md
docs/content/en/docs/topics/repair/_index.md

Correct port forwarding xrefs for SREs

---

docs/content/en/blog/articles/release-1.1/index.md

blog post for 1.1 release
**Checklist**

release 1.1 blog

---

docs/content/en/docs/getting-started/site-engineer/_index.md
docs/content/en/docs/topics/migration/_index.md
docs/content/en/docs/topics/upgrade/_index.md

Create separate Upgrade topic plus related edits

---

docs/content/en/docs/getting-started/developer/_index.md

Update section titles and fix intra-topic links

---

.github/workflows/sonarcloud.yaml
sonar-project.properties

Enable Sonarcloud static analysis when commits are pushed to `main`: https://sonarcloud.io/dashboard?id=k8ssandra_k8ssandra
We cannot enable this on PRs as it requires the SONAR_TOKEN which is stored in a secret, and secrets aren't available to external PRs.
Fixes #569
**Checklist**

Add sonarcloud analysis

---

docs/content/en/install/gke/gke.values.yaml

Switch GKE storageClass config guidance back to standard-rwo

---

docs/content/en/tasks/backup-restore/gcs/_index.md
docs/content/en/tasks/backup-restore/minio/_index.md

Google Cloud Storage info for Medusa backup/restore

---

README.md

Fixing broken links and adding links to code/docs contribution guides.
**Checklist**

Update README.md to fix broken links

---

CHANGELOG-1.2.md
charts/k8ssandra/values.yaml
tests/integration/scripts/collect_artifacts.sh
tests/unit/template_cassdc_test.go

Updates the 4.0 image to Cassnadra 4.0-rc1
Fixes #726
**Checklist**

Upgrade to Cassandra 4.0-rc1

---

docs/content/en/install/gke/_index.md

Include environment name in kubectl examples

---

docs/content/en/install/eks/_index.md
docs/content/en/install/eks/eks.values.yaml

EKS doc edits

---

CHANGELOG-1.2.md
README.md
charts/cass-operator/Chart.yaml
charts/cass-operator/README.md
charts/cass-operator/crds/customresourcedefinition.yaml
charts/cass-operator/values.yaml
contrib/upgrade-cass-operator.md
docs/content/en/docs/topics/ingress/traefik/tls/_index.md
docs/content/en/release-notes/_index.md
go.mod
go.sum
pkg/cleaner/cleaner.go
pkg/cleaner/cleaner_test.go
pkg/cleaner/suite_test.go
tests/integration/steps/integration_steps.go
tests/integration/steps/util.go
tests/unit/template_cassdc_test.go
tests/unit/utils/cassdc/containers.go
tests/unit/utils/cassdc/volumes.go

Updates cass-operator to v1.7.0
Fixes #693 
**Checklist**

Update cass-operator to v1.7.0

---

CHANGELOG-1.2.md
charts/k8ssandra/templates/cassandra/cassdc.yaml
charts/k8ssandra/values.yaml
tests/unit/template_cassdc_test.go

make allocate_tokens_for_replication_factor configurable

---

docs/assets/scss/_colab_styles.scss
docs/assets/scss/_variables_project.scss
docs/config.toml
docs/layouts/partials/footer.html

docs - footer style fixes - footer menu order

---

CHANGELOG-1.2.md
charts/k8ssandra/templates/cassandra/cassdc.yaml
charts/k8ssandra/templates/reaper/reaper.yaml
charts/k8ssandra/templates/stargate/stargate.yaml
charts/k8ssandra/values.yaml
charts/reaper-operator/crds/reaper.yaml
charts/reaper-operator/templates/role.yaml
charts/reaper-operator/values.yaml
go.mod
go.sum
tests/unit/template_cassdc_test.go
tests/unit/template_reaper_test.go
tests/unit/template_stargate_test.go
tests/unit/testdata/tolerations-values.yaml

Fixes #698, #673
**Checklist**

make tolerations configurable 

---

CONTRIBUTING.md
README.md

Fixes links to contribution guide in README.md and CANTRIBUTING.md 
n/a
**Checklist**

Fix links to contribiution guide

---

.github/workflows/integration-tests-release.yaml
Makefile
charts/cass-operator/Chart.yaml
charts/cass-operator/values.yaml
charts/k8ssandra/Chart.yaml
tests/integration/charts/cluster_full_stack.yaml
tests/integration/charts/cluster_with_medusa_local.yaml
tests/integration/charts/cluster_with_medusa_minio.yaml
tests/integration/charts/cluster_with_medusa_s3.yaml
tests/integration/charts/cluster_with_reaper.yaml
tests/integration/charts/cluster_with_stargate.yaml
tests/integration/charts/cluster_with_stargate_and_monitoring.yaml
tests/integration/scripts/collect_artifacts.sh
tests/integration/steps/integration_steps.go

Add TestUpgradeScenario to GHA integration test step, upgrades cass-operator to v1.7.1
**Checklist**

cass-operator v1.7.1, add TestUpgradeScenario to GHA

---

docs/content/en/install/local/_index.md

Added link to AKS from local install

---

cmd/k8ssandra-client/Dockerfile.it
pkg/crds/upgrade.go

Removes k8ssandra from the CRD path
**Checklist**

Remove k8ssandra from the path of CRDs and instead check all subpaths

---

docs/content/en/release-notes/_index.md
docs/package-lock.json
docs/package.json

Update RNs for 1.2.0

---

tests/integration/scripts/collect_artifacts.sh

Updates the `collect_artifacts.sh` script to use `kubectl cluster-info dump`.
Fixes #835
**Checklist**
- [] CHANGELOG.md updated (not required for documentation PRs)

use kubectl cluster-info dump to get logs

---

.github/workflows/integration-tests-release.yaml
docs/content/en/contribute/_index.md
tests/integration/steps/integration_steps.go

Enable CI on all branch pushes and allows setting the bucket name and region through env variable.
Fixes #860 
**Checklist**

Enable CI on push for all branches.

---

technical-docs/K8SSANDRA-OPERATOR-DESIGN.md

Migrating the K8ssandra Operator design document from Google Docs to an in-tree file for review and discussion.
An initial design approach for the build-out of a future K8ssandra Operator to replace a bulk of functionality currently provided by helm.
Fixes #719 
Fixes https://k8ssandra.atlassian.net/browse/K8SSAND-24
**Checklist**
┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-550) by [Unito](https://www.unito.io)

K8ssandra Operator design

---

technical-docs/K8SSANDRA-OPERATOR-DESIGN.md

**Checklist**
┆Issue is synchronized with this [Jira Bug](https://k8ssandra.atlassian.net/browse/K8SSAND-552) by [Unito](https://www.unito.io)

update operator design doc

---

docs/content/en/tasks/connect/ingress/k3d-deployment/_index.md

I got pretty confused walking through this today. It looks like there was some info from Kind docs and some things that weren't quite complete. It wasn't clear where the ports are bound, so I reworded quite a bit to be more instructive.
**Checklist**

A lot of clarification changes

---

docs/content/en/quickstarts/_index.md

Add AKS to linked list of cloud provider topics

---

tests/integration/steps/integration_steps.go

Modifies the integration tests to check the resource version change of the cassdc object during upgrades instead of waiting for the cassdc state to move to "Updating": if there's no change in the pod template spec in the upgrade, the cassdc object will not change state.
Fixes #862 
**Checklist**

Check resource version instead of cassdc state during upgrade

---

.github/workflows/publish-website.yaml

* Missed a change in the deploy part of the workflow that was still using the old script that was removed.
Fix the deploy portion of the docs building workflow.
**Checklist**

Really fix the docs builds this time

---

docs/content/en/quickstarts/developer/_index.md

Should go to /install/local#superuser
**Checklist**

Fix doc 404s

---

docs/content/en/quickstarts/site-reliability-engineer/_index.md

Should link to /install/local#superuser
Fixes #842
**Checklist**

Fixes issue #842, outdated link

---

.github/scripts/env_variables.sh
.github/workflows/dependency-upgrade.yaml
.github/workflows/integration-tests-release.yaml
.github/workflows/pr-main.yaml

Runs a schedule GHA workflow to send PRs for dependency upgrades (Stargate, Reaper, Medusa).
Fixes #886 
**Checklist**

Add workflow for creating dependency upgrade PRs

---

go.mod
go.sum
tests/integration/integration_suite_test.go
tests/integration/steps/reaper_steps.go

Refactor the Reaper ITs to use the Reaper go client.
Fixes #580 (K8SSAND-56)
**Checklist**

K8SSAND-56: Refactor the Reaper ITs to use the Reaper go client (fixes #580)

---

docs/config.toml

**What this PR does**: adds a link to the footer menu
**Checklist**

added brand footer link in docs

---

CHANGELOG-1.3.md
charts/k8ssandra/templates/stargate/stargate.yaml
charts/k8ssandra/values.yaml
tests/unit/template_stargate_test.go
tests/unit/testdata/affinity-values.yaml

make affinity configurable for stargate [K8SSAND-47]

---

CHANGELOG-1.3.md
charts/k8ssandra/Chart.yaml
charts/k8ssandra/templates/reaper/reaper.yaml
charts/k8ssandra/values.yaml
charts/reaper-operator/Chart.yaml
charts/reaper-operator/crds/reaper.yaml
charts/reaper-operator/templates/role.yaml
charts/reaper-operator/values.yaml
go.mod
go.sum
tests/unit/template_reaper_test.go
tests/unit/testdata/affinity-values.yaml

make affinity configurable for Reaper

---

CHANGELOG-1.3.md
charts/k8ssandra/values.yaml

Upgrade Medusa dependency 0.10.1 -> 0.11.0

---

CHANGELOG-1.3.md
charts/k8ssandra/values.yaml

Upgrade Stargate dependency 1.0.18 -> 1.0.29

---

examples/README.md
examples/multi-cassdc-single-k8s/README.md
examples/multi-cassdc-single-k8s/dc1.yaml
examples/multi-cassdc-single-k8s/dc2.yaml

Adding an examples directory to the main K8ssandra repo.
**Checklist**

adding examples dir and first example

---

tests/integration/steps/integration_steps.go

This PR forces the Traefik version in order to work around this issue:
https://github.com/traefik/traefik-helm-chart/issues/441
https://github.com/traefik/traefik-helm-chart/issues/441
**Checklist**

Temporarily force Traefik version

---

.github/workflows/integration-tests-release.yaml
CHANGELOG-1.3.md
charts/k8ssandra/templates/medusa/medusa-config.yaml
charts/k8ssandra/values.yaml
docs/content/en/contribute/_index.md
docs/content/en/install/aks/_index.md
docs/content/en/install/aks/aks.values.yaml
docs/content/en/tasks/backup-restore/_index.md
docs/content/en/tasks/backup-restore/azure/_index.md
tests/integration/charts/cluster_with_medusa_azure_blobs.yaml
tests/integration/integration_suite_test.go
tests/integration/steps/integration_steps.go
tests/integration/steps/medusa_steps.go
tests/unit/template_medusa_config_test.go

Adds support for Medusa Backups on Azure.
Fixes #685
**Checklist**

K8SSAND-32: Add support for Medusa backups on Azure (fixes #685)

---

tests/integration/integration_suite_test.go
tests/integration/steps/integration_steps.go
tests/integration/steps/util.go

A set of minor enhancements for K8ssandra integration tests.
Please check each individual commit comments for details on each change.
None
**Checklist**

Minor improvements to K8ssandra integration tests

---

.github/workflows/integration-tests-release.yaml

Fix working-directory

---

docs/content/en/install/local/_index.md

Update list of cloud providers

---

docs/content/en/install/eks/_index.md
docs/content/en/install/gke/_index.md

Add benchmark info and prereqs in EKS install plus misc GKE edits

---

CHANGELOG-1.4.md
charts/k8ssandra/templates/cassandra/cassdc.yaml
tests/unit/template_cassdc_test.go

Enhancements to support [k8ssand-695](https://k8ssandra.atlassian.net/browse/K8SSAND-695)
#959 
**Checklist**

Volume mount expansion for c*

---

docs/content/en/quickstarts/developer/_index.md

fixes an error when blindly copying and pasting examples
**Checklist**

removed 'cqlsh>' from prompt

---

.github/workflows/integration-tests-release.yaml

Switch to the newer structure of the setup-gcloud action.
**Checklist**

Update setup-gcloud action

---

docs/content/en/tasks/manage/_index.md
docs/content/en/tasks/manage/private-registries/_index.md

Add private registry info

---

docs/content/en/release-notes/_index.md

**Checklist**
┆Issue is synchronized with this [Jiraserver Task](https://k8ssandra.atlassian.net/browse/K8SSAND-758) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-758
┆Priority: Medium

Edit Medusa note based on more recent info

---

charts/k8ssandra/values.yaml
tests/unit/template_cassdc_test.go

* Merges 4.0.0 GA related content from 1.3 branch to main
* Switches to the latest version of the management-api
* Switches to 4.0.0 as the default database version
N/A
**Checklist**

Merge the 4.0.0 GA related commits from 1.3 into main

---

charts/k8ssandra/values.yaml
tests/unit/template_cassdc_test.go

This reverts commit f0786e77499e904978bf972061e114732e0ba3ab.
**Checklist**

Revert "Merge the 4.0.0 GA related commits from 1.3 into main (#1014)"

---

CHANGELOG-1.4.md
charts/cass-operator/crds/customresourcedefinition.yaml
charts/k8ssandra/README.md
charts/k8ssandra/values.yaml
charts/medusa-operator/crds/backup.yaml
docs/content/en/reference/helm-charts/k8ssandra/_generated.md

Fixes misspellings for jmv and reigistry.
Fixes #1018
[k8ssand-785](https://k8ssandra.atlassian.net/browse/K8SSAND-785)
**Checklist**

Corrected misspellings jmv and reigistry

---

charts/k8ssandra/values.yaml
tests/unit/template_cassdc_test.go
tests/unit/template_stargate_test.go

* Brings the default 4.0.0 functionality to main
* Addresses the missing test changes to account for the changed default from 3.11 -> 4.0 that I missed the first time
**Checklist**

Try the merge into main again

---

.vscode/settings.json
README.md
dev-guide.md
dev-quick-start.md

* Introduce some higher level introduction and learning elements
* Quick introduction to the development/planning process
* Overview of the code repos generally in play
* Incorporate the previous "Quick Start" inside of the new structure
N/A
**Checklist**

Restructure the developer "Quick Start" to be more of a general "Guide"

---

docs/content/en/release-notes/_index.md

Add Upgrade Notice re Cassandra num_tokens setting

---

docs/content/en/release-notes/_index.md

Min supported K8s version is 1.17

---

docs/content/en/install/local/_index.md

Update min K8s version to 1.17

---

CHANGELOG-1.4.md
charts/k8ssandra/templates/_helpers.tpl
charts/k8ssandra/templates/cassandra/cassdc.yaml
charts/k8ssandra/templates/reaper/reaper.yaml
charts/k8ssandra/values.yaml
charts/reaper-operator/crds/reaper.yaml
charts/reaper-operator/values.yaml
go.mod
go.sum
scripts/clean-ns.sh
tests/unit/template_cassdc_test.go
tests/unit/template_reaper_test.go
tests/unit/testdata/cassdc-security-context-custom-values.yaml
tests/unit/testdata/medusa-security-context-custom-values.yaml
tests/unit/testdata/reaper-security-context-custom-values.yaml
tests/unit/utils/cassdc/containers.go

Security context additions for K8ssandra containers and pods.
Fixes k8ssand-635 and k8ssand-732 as part of the [k8ssandra security epic](https://k8ssandra.atlassian.net/browse/K8SSAND-705)
**Checklist**
┆Issue is synchronized with this [Jiraserver Task](https://k8ssandra.atlassian.net/browse/K8SSAND-762) by [Unito](https://www.unito.io)
┆Issue Number: K8SSAND-762
┆Priority: Medium

Security enhancements

---

CHANGELOG-1.3.md
charts/k8ssandra/Chart.yaml
charts/k8ssandra/templates/_helpers.tpl
tests/integration/steps/integration_steps.go

Merges fixes from #1031 originally authored by @jsanda to 1.3.1 for release.
Fixes #1029  
**Checklist**

Merge fixes from 1031 to 1.3.1

---

tests/integration/charts/cluster_with_medusa_minio_upgraded.yaml
tests/integration/charts/cluster_with_reaper_upgraded.yaml
tests/integration/integration_suite_test.go

Fix upgrade tests (main branch)

---

docs/content/en/release-notes/_index.md

* Adds a small section for v1.3.1 to the release notes
* It does not do any re-work of the 1.3.0 specific content, we can address in a follow up as that's a broader thing
N/A
**Checklist**

v1.3.1 basic release notes

---

CHANGELOG-1.3.md

Merges the 1.3 changelog content to the main branch
N/A
**Checklist**

Merge 1.3 changelog updates to main

---

.gitignore
charts/cass-operator/Chart.yaml
charts/cass-operator/values.yaml
charts/k8ssandra-common/Chart.yaml
charts/k8ssandra-common/templates/_helpers.tpl
charts/k8ssandra/Chart.yaml
charts/k8ssandra/templates/_helpers.tpl
charts/k8ssandra/templates/cassandra/cassdc.yaml
charts/k8ssandra/templates/reaper/reaper.yaml
charts/k8ssandra/values.yaml
charts/medusa-operator/Chart.yaml
charts/medusa-operator/templates/deployment.yaml
charts/medusa-operator/values.yaml
charts/reaper-operator/Chart.yaml
charts/reaper-operator/templates/deployment.yaml
charts/reaper-operator/values.yaml
scripts/delete-crds.sh
tests/unit/template_cassdc_test.go
tests/unit/template_medusa_operator_test.go
tests/unit/template_reaper_operator_test.go
tests/unit/template_reaper_test.go
tests/unit/testdata/medusa-operator-security-context-custom-values.yaml
tests/unit/testdata/reaper-operator-security-context-custom-values.yaml

Security context for medusa and reaper operators within K8ssandra.
Covers security requirements as described in:
* [k8ssand-697](https://k8ssandra.atlassian.net/browse/K8SSAND-697)
* [k8ssand-696](https://k8ssandra.atlassian.net/browse/K8SSAND-696)
**Checklist**

Medusa and reaper operator securityContext

---

charts/k8ssandra-operator/.helmignore
charts/k8ssandra-operator/Chart.yaml
charts/k8ssandra-operator/README.md
charts/k8ssandra-operator/crds/apiextensions.k8s.io_v1_customresourcedefinition_clientconfigs.k8ssandra.io.yaml
charts/k8ssandra-operator/crds/apiextensions.k8s.io_v1_customresourcedefinition_k8ssandraclusters.k8ssandra.io.yaml
charts/k8ssandra-operator/crds/apiextensions.k8s.io_v1_customresourcedefinition_replicatedsecrets.k8ssandra.io.yaml
charts/k8ssandra-operator/crds/apiextensions.k8s.io_v1_customresourcedefinition_stargates.k8ssandra.io.yaml
charts/k8ssandra-operator/templates/configmap.yaml
charts/k8ssandra-operator/templates/deployment.yaml
charts/k8ssandra-operator/templates/leader-role.yaml
charts/k8ssandra-operator/templates/leader-rolebinding.yaml
charts/k8ssandra-operator/templates/role.yaml
charts/k8ssandra-operator/templates/rolebinding.yaml
charts/k8ssandra-operator/templates/serviceaccount.yaml
charts/k8ssandra-operator/values.yaml
charts/k8ssandra/Chart.yaml
charts/k8ssandra/values.yaml
scripts/update-helm-deps.sh

Adds a new chart that deploys k8ssandra-operator. Can be enabled with k8ssandra-operator/enabled=true in the values.yaml
Fixes #1046 , https://github.com/k8ssandra/k8ssandra-operator/issues/98
**Checklist**

k8ssandra-operator sub chart [K8SSAND-819]

---

docs/content/en/release-notes/_index.md

Clarify Upgrade Notices that workaround is specific to 1.3.0
**Checklist**

num_tokens upgrade bug fixed in K8ssandra 1.3.1

---

docs/content/en/tasks/backup-restore/azure/_index.md

To fix [azure storage credentials file](https://docs.k8ssandra.io/tasks/backup-restore/azure/#create-the-storage-account-credentials-file) json format
NA
**Checklist**

update docs for medusabackups azure json format

---

charts/k8ssandra-operator/templates/deployment.yaml

Add missing | quote

---

charts/k8ssandra-operator/Chart.yaml
charts/k8ssandra/Chart.yaml

Bump version of k8ssandra-operator chart for CRD issues

---

CHANGELOG-1.4.md
charts/cass-operator/Chart.yaml
charts/cass-operator/crds/customresourcedefinition.yaml
charts/cass-operator/templates/configmap.yaml
charts/cass-operator/templates/deployment.yaml
charts/cass-operator/templates/role.yaml
charts/cass-operator/values.yaml
charts/k8ssandra/Chart.yaml
charts/k8ssandra/values.yaml

Modifications for the cass-operator based on the next kubebuilder struct.
**Checklist**

Modify to use the cass-operator v1.8.0-rc.1

---

charts/cass-operator/README.md
charts/k8ssandra-common/README.md
charts/k8ssandra-operator/README.md
charts/k8ssandra/README.md
charts/medusa-operator/README.md
charts/reaper-operator/README.md
docs/content/en/reference/helm-charts/_index.md
docs/content/en/reference/helm-charts/k8ssandra-common/_generated.md
docs/content/en/reference/helm-charts/k8ssandra-operator/_generated.md
docs/content/en/reference/helm-charts/k8ssandra/_generated.md
docs/content/en/reference/helm-charts/medusa-operator/_generated.md
docs/content/en/reference/helm-charts/reaper-operator/_generated.md
docs/content/en/release-notes/_index.md

Update Helm v3 info and regen Helm chart ref docs

---

docs/content/en/tasks/migrate/_index.md

typo fixing

---

CHANGELOG-1.4.md
charts/k8ssandra/values.yaml

Upgrade Stargate dependency 1.0.29 -> 1.0.35

---

CHANGELOG-1.4.md
charts/cass-operator/Chart.yaml
charts/cass-operator/README.md
charts/cass-operator/values.yaml
charts/k8ssandra-operator/Chart.yaml
charts/k8ssandra/Chart.yaml
scripts/update-helm-deps.sh

Updates the cass-operator chart to v1.8.0 instead of release candidate version.
**Checklist**

Update to final version of cass-operator 1.8.0

---

CHANGELOG-1.4.md
charts/k8ssandra/values.yaml

Upgrade Stargate dependency 1.0.35 -> 1.0.40

---

dev-guide.md
dev-guidelines.md

**Summary**
Publish an initial version of a set of "Developer Guidelines" that discuss the process, roles, and expectations of the pull request/code review process within the project.
**What issue does this change address and why do we need it?**
This adds documentation to the project aimed at aligning one of our core development practice (code reviews) more directly with our community values.  The focus here is on behaviors and expectations, not so much process. It aims to help make the pull request/code review process a more engaging, productive, efficient, and positive experience for those involved in it.
**How does this address the issue?**
It aims to create some behavioral context for the process as well as establish some guidelines and expected behaviors for those involved.
**How …

Developer guidelines (primarily navigating the pr and code review process)

---

CHANGELOG-1.4.md
charts/k8ssandra/templates/stargate/stargate.yaml
charts/k8ssandra/values.yaml
tests/unit/template_stargate_test.go

Makes `JAVA_OPTS` configurable for Stargate
Fixes #1179 
**Checklist**

make JAVA_OPTS configurable for Stargate

---

CHANGELOG-1.4.md
charts/cass-operator/Chart.yaml
charts/cass-operator/crds/customresourcedefinition.yaml
charts/cass-operator/templates/configmap.yaml
charts/cass-operator/templates/leader_election_role.yaml
charts/cass-operator/templates/leader_election_role_binding.yaml
charts/cass-operator/templates/role.yaml
charts/cass-operator/values.yaml
charts/k8ssandra-operator/Chart.yaml
charts/k8ssandra/Chart.yaml

Upgrades cass-operator
Fixes #1193
**Checklist**

update to cass-operator 1.9.0

---

docs/content/en/release-notes/_index.md

Update RNs for K8ssandra 1.4.0

---

charts/cass-operator/README.md
charts/k8ssandra-operator/README.md
charts/k8ssandra/README.md
charts/medusa-operator/README.md
charts/reaper-operator/README.md
docs/content/en/reference/helm-charts/cass-operator/_generated.md
docs/content/en/reference/helm-charts/k8ssandra-operator/_generated.md
docs/content/en/reference/helm-charts/k8ssandra/_generated.md
docs/content/en/reference/helm-charts/medusa-operator/_generated.md
docs/content/en/reference/helm-charts/reaper-operator/_generated.md

Regenerated reference docs

---

CHANGELOG-1.5.md
charts/k8ssandra/values.yaml

Upgrade Stargate dependency 1.0.40 -> 1.0.44

---

docs/content/en/_index.md

Test edit on working branch based off common docs branch

---

.github/workflows/test-docs-build.yaml

Allow the PR based docs test check to run on the new docs branches
N/A
**Checklist**

Fix docs GHA

---

charts/k8ssandra-operator/Chart.yaml
charts/k8ssandra-operator/crds/cassandrabackups.medusa.k8ssandra.io_cassandrabackups.yaml
charts/k8ssandra-operator/crds/cassandrarestores.medusa.k8ssandra.io_cassandrarestores.yaml
charts/k8ssandra-operator/crds/config.k8ssandra.io_clientconfigs.yaml
charts/k8ssandra-operator/crds/k8ssandra.io_k8ssandraclusters.yaml
charts/k8ssandra-operator/crds/reaper.k8sandra.io_reapers.yaml
charts/k8ssandra-operator/crds/replication.k8ssandra.io_replicatedsecrets.yaml
charts/k8ssandra-operator/crds/stargate.k8ssandra.io_stargates.yaml
charts/k8ssandra-operator/templates/clusterrole.yaml
charts/k8ssandra-operator/templates/role.yaml
charts/k8ssandra-operator/values.yaml

Updates k8ssandra-operator chart with recent CRD and RBAC changes. Set the default operator version to 1.0.0-alpha.3 which will be released later today.
Fixes #1270
**Checklist**

update chart for 1.0.0-alpha.3 release of the operator [K8SSAND-1193]

---

docs/content/en/release-notes/_index.md

Update release notes to fix an hyperlink
**What this PR does**: Fixes the release notes trivial change
**Which issue(s) this PR fixes**: N/A
Fixes #<issue number> N/A
**Checklist**

Update release notes to fix an hyperlink

---

docs/content/en/tasks/scale/_index.md
docs/content/en/tasks/secure/_index.md
docs/content/en/tasks/secure/encryption/_index.md

Enabling encryption topic, content from Alex

---

charts/cass-operator/Chart.yaml
charts/cass-operator/crds/cassandrtasks.yaml
charts/cass-operator/templates/configmap.yaml
charts/cass-operator/values.yaml

update to cass-operator v1.10.0

---

charts/k8ssandra-operator/Chart.yaml
charts/k8ssandra-operator/crds/k8ssandra-operator-crds.yaml
charts/k8ssandra-operator/templates/deployment.yaml
charts/k8ssandra-operator/templates/issuer.yaml
charts/k8ssandra-operator/templates/role.yaml
charts/k8ssandra-operator/templates/validatingwebhookconfiguration.yaml
charts/k8ssandra-operator/templates/webhook-service.yaml
charts/k8ssandra-operator/templates/webhook-serving-cert.yaml
charts/k8ssandra-operator/values.yaml

update k8ssandra-operator to v1.0.0

---

docs/assets/scss/_colab_styles.scss
docs/layouts/partials/navbar-version-selector.html
docs/layouts/partials/navbar.html

Cherry pick #1316 into `docs-v1`
Fixes #1317 for `docs-v1`
**Checklist**

Fix version drop down on mobile resolutions [K8SSAND-1289]

---

docs/content/en/_index.md
docs/content/en/components/cass-operator/_index.md
docs/content/en/components/k8ssandra-operator/_index.md
docs/content/en/components/medusa/_index.md
docs/content/en/components/metrics-collector/_index.md
docs/content/en/components/reaper/_index.md
docs/content/en/components/stargate/_index.md
docs/content/en/faqs/_index.md
docs/content/en/glossary/_index.md
docs/content/en/install/_index.md
docs/content/en/install/aks/_index.md
docs/content/en/install/doks/_index.md
docs/content/en/install/eks/_index.md
docs/content/en/install/gke/_index.md
docs/content/en/install/local/_index.md
docs/content/en/quickstarts/_index.md
docs/content/en/quickstarts/developer/_index.md
docs/content/en/quickstarts/site-reliability-engineer/_index.md
docs/content/en/reference/_index.md
docs/content/en/release-notes/_index.md
docs/content/en/tasks/_index.md

Updates in Release Notes

---

docs/content/en/install/local/_index.md
docs/content/en/install/local/multi-cluster-helm/_index.md
docs/content/en/install/local/multi-cluster-kustomize/_index.md
docs/content/en/install/local/single-cluster-helm/_index.md
docs/content/en/install/local/single-cluster-kustomize/_index.md

Cleanup text and helm repo add where needed

---

docs/content/en/release-notes/_index.md

Update Release Notes deployed components include Cassandra 4.0.3

---

CHANGELOG-1.5.md
charts/k8ssandra/templates/medusa/medusa-config.yaml
charts/k8ssandra/values.yaml

Upgrade Medusa dependency 0.11.3 -> 0.12.1

---

docs/content/en/tasks/secure/_index.md

Updates the security tasks documentation for v2.
Fixes #1370
**Checklist**

Update the security tasks documentation for v2

---

.vscode/settings.json
docs/content/en/tasks/repair/_index.md

Updates Reaper documentation for v2 (k8ssandra-operator).
Fixes #1368 
**Checklist**

Update Reaper's documentation for v2

---

charts/k8ssandra-operator/Chart.yaml
charts/k8ssandra-operator/crds/k8ssandra-operator-crds.yaml
charts/k8ssandra-operator/templates/role.yaml
charts/k8ssandra-operator/values.yaml

Upgrade k8ssandra-operator dependency 1.0.2 -> 1.1.1

---

CHANGELOG-1.6.md
charts/k8ssandra/templates/_helpers.tpl

fix G1GC property value

---

docs/content/en/_index.md

Adds a compatibility matrix between Kubernetes and K8ssandra versions on the landing page of the documentation.
Fixes [#561](https://github.com/k8ssandra/k8ssandra-operator/issues/561)
**Checklist**

Add k8s compatibility matrix

---

charts/k8ssandra-operator/Chart.yaml
charts/k8ssandra-operator/crds/k8ssandra-operator-crds.yaml
charts/k8ssandra-operator/templates/clusterrole.yaml
charts/k8ssandra-operator/templates/role.yaml
charts/k8ssandra-operator/values.yaml

Upgrades the k8ssandra-operator chart to v1.2.0 and cut out the Helm release.
**Checklist**

Upgrade k8ssandra-operator to v1.2.0

---

docs/content/en/tasks/backup-restore/_index.md

What it says in the title.
Fixes #1454 
**Checklist**

Update the Medusa documentation for v1.2

---

charts/k8ssandra-operator/Chart.yaml
charts/k8ssandra-operator/templates/deployment.yaml
charts/k8ssandra-operator/templates/issuer.yaml
charts/k8ssandra-operator/templates/validatingwebhookconfiguration.yaml
charts/k8ssandra-operator/templates/webhook-service.yaml
charts/k8ssandra-operator/templates/webhook-serving-cert.yaml

Enables admissionReview endpoint for MedusaBackupSchedule webhook in the non-controlPlane cluster.
Fixes #1495 
**Checklist**

Add MedusaBackupSchedule endpoint

---

docs/content/en/supported-software/_index.md

per Karan's request and info from Chris B
**Checklist**

Supported software page

---

docs/content/en/tasks/scale/_index.md

Adds documentation on bootstrap and decommission order
None
**Checklist**

Add documentation on bootstrap and decommission order

---

docs/content/en/reference/crd/cass-operator-crds-latest/_index.md
docs/content/en/reference/crd/k8ssandra-operator-crds-latest/_index.md
docs/content/en/reference/crd/releases/k8ssandra-operator-releases/k8ssandra-operator-crds-1.3/_index.md

This is an auto-generated PR from the K8ssandra CRD reference update GHA workflow.

Upgrade CRD reference 3e66201c-cb80a5a4

---

.github/workflows/integration-tests-release.yaml
charts/k8ssandra-operator/Chart.yaml
charts/k8ssandra-operator/crds/k8ssandra-operator-crds.yaml
charts/k8ssandra-operator/templates/clusterrole.yaml
charts/k8ssandra-operator/templates/role.yaml
charts/k8ssandra-operator/values.yaml
tests/integration/steps/integration_steps.go

Upgrade k8ssandra-operator dependency 1.2.1 -> 1.3.0

---

.github/workflows/add_to_project.yaml
.github/workflows/check_pr_linked_issue.yaml
.github/workflows/dependency-upgrade.yaml
.github/workflows/update-crd-reference.yaml

Adds GHA workflows to:
- add new issues to the GH project board
- check that PRs have linked issues
**Checklist**

Add GH projects automation

---

charts/k8ssandra-operator/Chart.yaml
charts/k8ssandra-operator/crds/k8ssandra-operator-crds.yaml
charts/k8ssandra-operator/values.yaml

Upgrade k8ssandra-operator dependency 1.3.0 -> 1.4.0

---

CHANGELOG-1.6.md
charts/k8ssandra/Chart.yaml
charts/medusa-operator/Chart.yaml
charts/reaper-operator/Chart.yaml
tests/unit/utils/helm/helm.go

What it says on the tin.
#1537 
**Checklist**

Deprecations of k8ssandra 1.x.

---

CHANGELOG-1.5.md
charts/k8ssandra/values.yaml

Upgrades Grafana to the latest Apache Licensed version.
**Checklist**

Upgrade Grafana to v7.5.17

---

docs/content/en/reference/crd/cass-operator-crds-latest/_index.md
docs/content/en/reference/crd/releases/k8ssandra-operator-releases/k8ssandra-operator-crds-1.4/_index.md

This is an auto-generated PR from the K8ssandra CRD reference update GHA workflow.

Upgrade CRD reference 4e81c4da-dddc47c4

---

docs/content/en/reference/crd/k8ssandra-operator-crds-latest/_index.md

This is an auto-generated PR from the K8ssandra CRD reference update GHA workflow.

Upgrade CRD reference 6195f771-a07ca5eb

---

charts/k8ssandra-operator/Chart.yaml
charts/k8ssandra-operator/crds/k8ssandra-operator-crds.yaml
charts/k8ssandra-operator/templates/clusterrole.yaml
charts/k8ssandra-operator/templates/role.yaml
charts/k8ssandra-operator/values.yaml

Upgrade k8ssandra-operator dependency 1.4.1 -> 1.5.0

---

charts/cass-operator/Chart.yaml
charts/cass-operator/UPGRADE.md
charts/cass-operator/crds/cassandradatacenter.yaml
charts/cass-operator/crds/cassandratasks.yaml
charts/cass-operator/templates/configmap.yaml
charts/cass-operator/values.yaml
charts/k8ssandra-operator/Chart.yaml

Update cass-operator chart to v1.14.0

---

charts/k8ssandra-operator/Chart.yaml

Update cass-operator helm chart for k8ssandra-operator v1.5.0

---

.github/workflows/test-docs-build.yaml
docs/config/development/config.toml
docs/config/production-v1/config.toml
docs/config/staging-v1/config.toml

**What this PR does**: cleanup in docs-v1
Fixes #1586 
**Checklist**

added cleanup in docs-v1

---

charts/cass-operator/Chart.yaml
charts/cass-operator/templates/configmap.yaml
charts/cass-operator/values.yaml

Fixes the rendering of ImagePullSecret in the ConfigMap
Fixes #1601 
**Checklist**

Fix ImagePullSecret in ImageConfig

---

charts/cass-operator/Chart.yaml
charts/cass-operator/crds/cassandradatacenters.yaml
charts/cass-operator/crds/cassandratasks.yaml
charts/cass-operator/templates/configmap.yaml
charts/cass-operator/templates/deployment.yaml
charts/cass-operator/values.yaml

Updates cass-operator chart to v1.16.0
**Checklist**

Update to cass-operator v1.16.0

---

charts/cass-operator/Chart.yaml
charts/cass-operator/values.yaml

Update cass-operator to 1.17.2

---

.github/workflows/integration-tests-release.yaml

Remove deprecated use of ::set-output

---

charts/cass-operator/Chart.yaml
charts/cass-operator/crds/cassandratasks.yaml
charts/cass-operator/values.yaml

cass-operator v1.18.1

---

charts/cass-operator/Chart.yaml
charts/cass-operator/values.yaml

Update to cass-operator v1.18.2

---

charts/cass-operator/Chart.yaml
charts/cass-operator/templates/configmap.yaml
charts/cass-operator/values.yaml

Change the image pull registeries.
Fixes #1636 
**Checklist**

Pull from cr.k8ssandra.io and cr.dtsx.io

---

charts/cass-operator/Chart.yaml
charts/cass-operator/templates/configmap.yaml
charts/cass-operator/templates/deployment.yaml
charts/cass-operator/templates/validatingwebhookconfiguration.yaml
charts/cass-operator/templates/webhook-service.yaml
charts/cass-operator/values.yaml

What it says in the title.
Fixes #1640 
**Checklist**

Allow disabling the cert-manager check in cass-operator's helm charts

---

charts/cass-operator/Chart.yaml
charts/cass-operator/crds/cassandradatacenters.yaml
charts/cass-operator/values.yaml

Can be merged once this job completes: 
https://github.com/k8ssandra/cass-operator/actions/runs/8003715081/job/21859601651
**Checklist**

Release cass-operator v1.19.0 chart

---

charts/cass-operator/Chart.yaml
charts/cass-operator/values.yaml

Update to cass-operator v1.19.1

---

charts/cass-operator/Chart.yaml
charts/cass-operator/values.yaml

Push chart to version 0.47.2

---

charts/cass-operator/Chart.yaml
charts/cass-operator/crds/cassandradatacenters.yaml
charts/cass-operator/values.yaml

Updates cass-operator to v1.21.0
@adejanovski 
**Checklist**

Update to cass-operator v1.21.0

---

charts/cass-operator/Chart.yaml
charts/cass-operator/templates/configmap.yaml

Add missing HCD repository to the imageConfig

---

charts/cass-operator/Chart.yaml
charts/cass-operator/values.yaml

Release cass-operator chart 0.52.2 (v1.21.1)

---

charts/cass-operator/Chart.yaml
charts/cass-operator/templates/configmap.yaml

Fix typo in the ConfigMap for ImageConfig

---

charts/cass-operator/Chart.yaml
charts/cass-operator/values.yaml

values.yaml was missing correct image, update to v1.22.0

---

charts/cass-operator/Chart.yaml
charts/cass-operator/values.yaml

cass-operator to v1.22.1
**Checklist**

cass-operator v1.22.1

---

charts/cass-operator/Chart.yaml
charts/cass-operator/values.yaml

cass-operator v1.22.2

---

charts/cass-operator/Chart.yaml
charts/cass-operator/values.yaml

Release cass-operator v1.22.3

---

charts/cass-operator/Chart.yaml
charts/cass-operator/values.yaml

Release cass-operator v1.22.4

---

charts/cass-operator/Chart.yaml
charts/cass-operator/crds/cassandradatacenters.yaml
charts/cass-operator/templates/configmap.yaml
charts/cass-operator/values.yaml

Release cass-operator v1.23.0

---

charts/cass-operator/Chart.yaml
charts/cass-operator/values.yaml

Release cass-operator v1.23.1

---

charts/cass-operator/Chart.yaml
charts/cass-operator/values.yaml

Release cass-operator v1.23.2

---

charts/cass-operator/Chart.yaml
charts/cass-operator/values.yaml

Set allowPrivilegeEscalation=false as default for cass-operator

---

charts/cass-operator/Chart.yaml
charts/cass-operator/crds/cassandradatacenters.yaml
charts/cass-operator/crds/cassandratasks.yaml
charts/cass-operator/crds/scheduledtasks.yaml
charts/cass-operator/templates/role.yaml
charts/cass-operator/values.yaml

Release cass-operator v1.24.0 with legacy CRD procedure still.
**Checklist**

Release cass-operator v1.24.0

---

charts/cass-operator/Chart.yaml
charts/cass-operator/templates/configmap.yaml

Support templating for the imagePullSecret property in ImageConfig

---

charts/k8ssandra/Chart.yaml
charts/medusa-operator/Chart.yaml
charts/reaper-operator/Chart.yaml

Update outdated charts

---

charts/cass-operator/Chart.yaml
charts/cass-operator/templates/_helpers.tpl
charts/cass-operator/templates/deployment.yaml
charts/cass-operator/templates/validatingwebhookconfiguration.yaml
charts/cass-operator/values.yaml

Add watchNamespaces restrictions for clusterScoped installations

---

charts/cass-operator/Chart.yaml
charts/cass-operator/crds/scheduledtasks.yaml
charts/cass-operator/values.yaml

Release cass-operator v1.24.1

---

charts/cass-operator/Chart.yaml
charts/cass-operator/crds/cassandradatacenters.yaml
charts/cass-operator/crds/cassandratasks.yaml
charts/cass-operator/crds/scheduledtasks.yaml
charts/cass-operator/templates/role.yaml
charts/cass-operator/values.yaml

Release cass-operator v1.26.0
