k8ssandra/k8ssandra

charts/backup/Chart.yaml, charts/k8ssandra-cluster/Chart.yaml, charts/k8ssandra-cluster/templates/grafana/instance.yaml, charts/k8ssandra-cluster/values.yaml, charts/k8ssandra/Chart.yaml, charts/restore/Chart.yaml
Fixes #71 
This PR exposes the `root_url` and `serve_from_sub_path` settings in `/etc/grafana/grafana.ini`. 
I tested as follows:
```
$ helm install grafana-config ./k8ssandra-cluster -f grafana-values.yaml
```
where `grafana-values.yaml` looks like this:
```yaml
monitoring:
grafana:
config:
server:
rootUrl: http://localhost:3000
serveFromSubPath: true
```
=> [GH 71] expose root_url and serve_from_sub_path settings

charts/backup/Chart.yaml, charts/k8ssandra-cluster/Chart.yaml, charts/k8ssandra-cluster/templates/prometheus/prometheus.yaml, charts/k8ssandra-cluster/values.yaml, charts/k8ssandra/Chart.yaml, charts/restore/Chart.yaml
Fixes #90 
To test,
```
$ helm install k8ssandra-tools ./k8ssandra
$ helm install prom-config ./k8ssandra-cluster -f prom-values.yaml
```
where `prom-values.yaml` looks like this:
```yaml
monitoring:
prometheus:
externalUrl: localhost
```
=> [GH 90] make prometheus external url configurable

charts/backup/Chart.yaml, charts/k8ssandra-cluster/Chart.yaml, charts/k8ssandra-cluster/templates/cassdc.yaml, charts/k8ssandra-cluster/values.yaml, charts/k8ssandra/Chart.yaml, charts/restore/Chart.yaml
The original chart didn't allow for the persistentVolume to be configurable. 
It is particularly useful to allow the configuration for 
- storageClass
- storage request
since the `standard` storageClass is not always present and must be created  (k3d for instance has only support for a local-path provisioner, Openshift is usually installed with glusterfs-storage,...) .
I added the following section in the default values file:
```yaml
name: k8ssandra
clusterName: k8ssandra
datacenterName: dc1
size: 1
k8ssandra:
namespace: default
name: k8ssandra
persistentVolume:
storageClass: standard
size: 5Gi
...
```
allowing the configuration with  standard helm values override.
I didn't touch the `accessModes`  since I assume that `ReadWriteOnce` must not be changed for K8ssandra use case.
=> Added storageClass and PV size to Helm values for external customisation

charts/k8ssandra-cluster/values.yaml
This make the ingress enabled property consistent across the various services.
=> Cassandra ingress should be enabled by default

charts/k8ssandra-cluster/templates/cassdc.yaml, tests/unit/template_cassdc_test.go
Env nor InitContainers should be present if Reaper and Medusa are disabled, fixes #135
=> If no Reaper or Medusa is present, do not render empty slices

docs/assets/scss/_variables_project.scss, docs/content/en/_index.md
* Small layout issue in the docs that Chris mentioned to me earlier
* Core of the problem is FF's sizing of images within flex containers, it behaves differently than Chrome and Safari (I didn't try Edge)
* The template that we use includes these cards, which get a flex display applied to them, in this particular case there is no necessity for that, so I've forced the display in those cased only back to the default.
* This same change also fixed a wrapping issue with the cards that I noticed - that happens on all browsers, not just FF
FF Icon Issue Before and After:
Card Wrapping Issue Before and After:
=> Fix layout issues of home screen cards

charts/k8ssandra-cluster/templates/cassdc.yaml, tests/unit/template_cassdc_test.go
Image from DataStax Docker image v0.1.17 `cassandra-mgmtapi-3_11_7:v0.1.17`
=> Version and image target updated

charts/k8ssandra-cluster/values.yaml, tests/unit/template_cassdc_test.go
Expansion on [PR#160](https://github.com/k8ssandra/k8ssandra/pull/160).
- Documented relationship of k8ssandra `allowMultipleNodesPerWorker` and `resources`
- If enabled, k8ssandra `resources.limits` and `resources.requests` must be defined.
=> Configurable Resources Additions

.github/workflows/main.yaml, .github/workflows/release.yaml
Fixes #145 
As has been discussed previously it does not make sense to require the versions to be the same across all charts. We do want to follow the practice of bumping the version when is modified. This PR does not include a check for that.
As a follow up to this, we should tackle #145 whereby pushing a git tag would result in charts being pushed to a _stable_ chart repo.
=> remove chart version checks

charts/k8ssandra/Chart.yaml, charts/k8ssandra/values.yaml
This property moved under the datacenters objects.
=> Remove obsolete cassandra.size property

charts/k8ssandra/Chart.yaml, charts/k8ssandra/templates/medusa-config.yaml
With the Medusa image upgrade, there is a new config setting that we need to make sure is set. It basically tells Medusa it is running in k8s which will in turn cause Medusa to use Jolokia (and later the management-api) instead of nodetool.
=> need to make sure the enabled flag for kubernetes is set

charts/k8ssandra/templates/cassandra/cassdc.yaml, charts/k8ssandra/values.yaml, go.mod, go.sum, tests/unit/template_cassdc_test.go
Provides cluster, dc, and default jvm heap option configurations as described in #158.
[Design Notes](https://github.com/k8ssandra/k8ssandra/issues/158#issuecomment-765010492)
=> JVM options heap inclusion

charts/k8ssandra/templates/stargate/service.yaml, charts/k8ssandra/templates/stargate/service_monitor.yaml, charts/k8ssandra/templates/stargate/stargate.yaml
The Stargate ServiceMonitor was merged as part of the original Stargate PR, but it wasn't quite right and Prometheus wasn't picking it up. This PR resolves those issues.
Fixes #164
**Checklist**
=> #164: adding correct labels for Prometheus to pick up the Stargate ServiceMonitor

charts/k8ssandra/dashboards/stargate.json, charts/k8ssandra/templates/grafana/configmap.yaml
Creates an initial Grafana dashboard for Stargate, as shown below. It's not much, but it's functional and useful. There's certainly room to iterate on it more, but I needed at least this much in order to make progress on #249.
Note that the changes from #281 are also needed in order for there to be any data behind this dashboard.
Fixes #165
**Checklist**
=> #165: adding initial Grafana dashboard for Stargate

docs/content/en/docs/topics/accessing-services/repair/_index.md
Projects and domain names can not use "Cassandra".
It is "Reaper" or "Reaper for Apache Cassandra".
https://www.apache.org/foundation/marks/faq/#products
https://apache.org/foundation/marks/#domains
=> Fix trademark violation

charts/k8ssandra/templates/traefik.ingressroutes.yaml, docs/content/en/docs/topics/ingress/traefik/kind-deployment/kind.config.yaml
Non-Stargate Cassandra ingress was broken. Now it isn't. :) 
Fixes #293
**Checklist**
=> fixed c* ingress

charts/k8ssandra/Chart.yaml, charts/k8ssandra/values.yaml
Makes sure that the `prometheusSpec` property is set properly in order to eliminate the Helm warnings. This is done by uncommenting the `routePrefix` and `externalUrl` properties. I set them to their default values define in the kube-prometheus-stack chart.
Fixes #295
**Checklist**
=> set prometheusSpec to a value and add some comments

charts/k8ssandra/Chart.yaml, charts/k8ssandra/templates/cassandra/cassdc.yaml, charts/k8ssandra/templates/cassandra/superuser-secret.yaml, tests/unit/template_superuser_secret_test.go
Fixes #261 by not generating a secret or set superUsername in CassandraDatacenter if auth is disabled
Fixes #261
**Checklist**
=> Do not generate secret or set superUsername if auth is disabled

charts/k8ssandra/Chart.yaml, charts/k8ssandra/templates/cassandra/cassdc.yaml, tests/unit/template_cassdc_test.go
Stops using subPath volume mounts for the medusa configmap
Fixes #328 
**Checklist**
=> don't use subPath mounts and update tests

.github/workflows/pr-main.yaml, .github/workflows/publish-website.yaml, .github/workflows/regenerate-reference-docs.yaml
Fixes an issue with the previously used relative path and actions which leverage `working_directory`.
**Checklist**
**Before**
**After**
(Note the deploy failure is due to running in a separate repo without GCS credentials, the commands run able to execute which fixes the problem here.)
=> Absolute PATH adjustments

charts/k8ssandra/Chart.yaml, charts/k8ssandra/templates/cassandra/cassdc.yaml, tests/unit/template_cassdc_test.go
Adds a if clause to the cassdc.yaml template to prevent rendering of empty "users" definition in CassandraDatacenter.
Fixes #334 
**Checklist**
=> If stargate, medusa and reaper are disabled, do not render users.

charts/k8ssandra/Chart.yaml, charts/k8ssandra/templates/cassandra/cassdc.yaml, charts/k8ssandra/templates/medusa/medusa-config.yaml, charts/k8ssandra/values.yaml, tests/unit/template_medusa_config_test.go
Adds the ability to set region for AWS as well as use S3 compatible storage options that are not AWS S3.
Fixes #142 
**Checklist**
=> Add ability to define s3_compatible settings as well as aws region

charts/k8ssandra/Chart.yaml, charts/k8ssandra/templates/_helpers.tpl, charts/k8ssandra/templates/cassandra/cassdc.yaml, charts/k8ssandra/values.yaml, tests/unit/template_cassdc_test.go
Overrides the num_tokens in cass-operator by setting it to a default value as defined in the used version. This would be 256 for 3.11.* and 16 for 4.0*. Also allows overriding to set a defined value.
Fixes #324 
**Checklist**
=> Set the default value of tokens for each supported version

docs/config.toml
Enabling the `prism_syntax_highlighting` option in the doc site configuration makes it possible to copy/paste content from tutorials, which makes the tutorials easier to consume.
=> enable copying of code samples in docs

Makefile, charts/k8ssandra/Chart.yaml, charts/k8ssandra/templates/_helpers.tpl, charts/k8ssandra/templates/cassandra/cassdc.yaml, charts/k8ssandra/values.yaml, tests/unit/template_cassdc_test.go, tests/unit/testdata/cluster-g1-dc-cms-values.yaml, tests/unit/testdata/dc-gc-cms-values.yaml, tests/unit/testdata/dc-gc-g1-values.yaml
Makes GC configurable
Fixes #220
**Checklist**
=> Make garbage collection configurable

charts/k8ssandra/Chart.yaml, charts/k8ssandra/templates/stargate/stargate.yaml, charts/k8ssandra/values.yaml, docs/content/en/docs/faqs/_index.md, tests/unit/template_stargate_test.go
Adds support for Stargate to run the correct image and supply the correct CLUSTER_VERSION when using Cassandra 4.0
Fixes #397 
**Checklist**
=> 397 support cass4 with stargate

charts/k8ssandra/Chart.yaml, charts/k8ssandra/values.yaml
Updates default Reaper version to 2.2.0
Fixes #391 
**Checklist**
=> Update Reaper to version 2.2.0

charts/k8ssandra/Chart.yaml, charts/k8ssandra/values.yaml, docs/content/en/docs/faqs/_index.md, tests/unit/template_stargate_test.go
Upgrades Stargate to 1.0.9
Adds a bit of clarity to the doc comment for stargate.version
This is in draft mode because the images for 1.0.9 have not yet been published to Docker Hub. The changes themselves should be final, but I need to test with a cluster using the actual images.
None
**Checklist**
=> Upgrade Stargate and improve doc comments for stargate.image

Makefile
Adds TESTS parameter to the Makefile, allowing the following behavior:
```
⋊> ~/p/g/d/k8ssandra on main ⨯ make TESTS=".*auth.*" unit-test                                                                                                                                                                                                                           09:01:49
go test -v -test.timeout=3m ./tests/unit/... -coverprofile cover.out -args -ginkgo.focus=".*auth.*"
=== RUN   TestTemplateUnitTests
Running Suite: Unit tests suite
===============================
Random Seed: 1613977317
Will run 7 of 126 specs
```
With just ``make unit-test`` all unit tests (template tests basically) are run and ``make test`` behavior will remain the same as before. ``make pkg-test`` allows …
=> Allow to run subset of unit tests

charts/k8ssandra/Chart.yaml, charts/k8ssandra/templates/reaper/ingress.yaml, tests/unit/template_reaper_ingress_test.go
* Talked with @jsanda about this one and he explained that the recent changes in reaper-operator necessitated a change to the structure of the service name deployed
* This brings the name in-line with what reaper-operator produces and updates the tests
Fixes #431 
**Checklist**
=> Update name of service routed to by reaper ingress rule

charts/k8ssandra/Chart.yaml, charts/k8ssandra/templates/_helpers.tpl, charts/k8ssandra/templates/cassandra/cassdc.yaml, charts/k8ssandra/templates/reaper/reaper.yaml
This makes the logic consistent across the `k8ssandra.<component>UserSecretName` templates. It also updates the code that calls these templates.
**Checklist**
=> make secret name templates consistent

scripts/helm-version.py
Add new parameter --chart to update a single chart version instead of all of them.
```
⋊> ~/p/g/d/k8ssandra on main ⨯ scripts/helm-version.py --incr minor --chart medusa-operator                                                                                                                                                                                               14:42:35
Updated /home/michael/projects/git/datastax/k8ssandra/charts/medusa-operator/Chart.yaml to 0.29.0
⋊> ~/p/g/d/k8ssandra on main ⨯
```
**Checklist**
=> Add ability to define a single chart to update with the version script

scripts/helm-version.py, scripts/image-update.py
Adds the ability to update the default image tag in values.yaml for an operator. Works with cass-operator, reaper-operator and medusa-operator. 
```
➜  k8ssandra git:(main) ✗ scripts/image-update.py --chart medusa-operator --tag asddsa
Updated medusa-operator to use docker.io/k8ssandra/medusa-operator:asddsa
➜  k8ssandra git:(main) ✗
```
Also updates some descriptions and indentation fixes.
**Checklist**
=> Add a script to update operator image tag

charts/k8ssandra/Chart.yaml, charts/k8ssandra/templates/medusa/medusa-config.yaml
Allows to pass credentials to s3 compatible Medusa backends (aside from AWS S3).
Fixes #487
**Checklist**
=> Fix passing credentials to S3 compatible backends in Medusa

CHANGELOG.md, charts/k8ssandra/Chart.yaml, charts/k8ssandra/values.yaml, tests/unit/template_cassdc_test.go
This simply updates Management API image versions to pickup the fix for missing/unwriteable `$HOME` directory.
Fixes #396 
**Checklist**
=> Update management api images to fix cqlsh warnings

docs/content/en/docs/_index.md
**Checklist**
This PR removes the _What is K8ssandra not yet good for?_ section. The content is incorrect. It says:
>Right now K8ssandra is deployed as an entire stack. It currently assumes your deployment uses the entire stack. Trading out certain components for others is not supported. 
This is wrong. We do not deploy all components by default. For example, Medusa and Traefik are disabled by default. Secondly, there is no assumption about the entire stack being used since it is possible to disable components. Lastly, it is entirely possible to swap out components. There is nothing to prevent you from swapping out the monitoring bits for example. In fact, I would consider this a feature. 
I think it is better …
=> remove what k8ssandra is not good for section

CHANGELOG.md, charts/k8ssandra/Chart.yaml, charts/k8ssandra/templates/_helpers.tpl, charts/k8ssandra/templates/cassandra/cassdc.yaml, tests/unit/template_cassdc_test.go, tests/unit/utils/cassdc/volumes.go
This PR adds an init container that sets up the initial Cassandra config in `/etc/cassandra` from the base Cassandra image. Previously, when enabling Medusa, `/etc/cassandra` would be shadow mounted with an empty directory and only config-builder contents would be copied to `/etc/cassandra`, resulting in a fair amount of missing config.
Fixes #475 
**Checklist**
=> Fix Cassandra config clobbering when enabling Medusa

CHANGELOG.md, charts/k8ssandra/Chart.yaml, charts/k8ssandra/templates/cassandra/cassdc.yaml, charts/k8ssandra/values.yaml, tests/unit/template_cassdc_test.go
Adds new spec parameter for CassandraDatacenter, "additionalSeeds"
Fixes #547 
**Checklist**
=> Allow defining additionalSeeds

tests/integration/charts/one_node_cluster_with_medusa_minio.yaml, tests/integration/charts/one_node_cluster_with_medusa_s3.yaml, tests/integration/charts/three_nodes_cluster_full_stack.yaml, tests/integration/charts/three_nodes_cluster_with_reaper.yaml, tests/integration/charts/three_nodes_cluster_with_stargate.yaml, tests/integration/charts/three_nodes_cluster_with_stargate_and_monitoring.yaml
A couple days ago we merged #544. Tests runs really slowly in large part due to Cassandra pods taking a long time to terminate. See the following for more details on why tests run slowly:
* https://github.com/datastax/cass-operator/issues/325
* https://github.com/thelastpickle/cassandra-medusa/pull/313
When I ran `TestFullStackScenario` from main it took 1462.983s. From this branch it took 1043.537s. That is more than a 7 minute difference! 
**Checklist**
=> speed up tests with faster C* pod termination

.github/pull_request_template.md, .github/workflows/release-next.yaml, .github/workflows/release-stable.yaml, charts/k8ssandra/Chart.yaml
Automates Helm chart version number management for the next channel.
We're moving to using a fixed `x.x.x-SNAPSHOT` Helm chart version as long as it is unreleased. Pushes to main trigger a helm release on the next channel, and this PR implements a hot replacement of the version with `x.x.x-<datetime>-<git sha>`.
A check was added to the stable release workflow which verifies that the helm chart version (which should be manually updated before release) and the tag name match.
A problem was spotted with the cache that's being used for the `helm` and `yq` binaries: since the install uses a script, we need to perform a checkout in case we get a cache miss. It wasn't the case in the next workflow, which led to some failures.
The install being very fast (checkout + …
=> Automate helm chart version management on releases

CHANGELOG.md, charts/k8ssandra/templates/cassandra/cassdc.yaml, charts/k8ssandra/templates/stargate/service.yaml, charts/k8ssandra/templates/stargate/stargate.yaml, charts/k8ssandra/values.yaml, tests/unit/template_cassdc_test.go, tests/unit/template_stargate_test.go
Adds enabled flag under cassandra section in values.yaml which controls if the Cassandra cluster should be installed or not. This allows to install only operators for example, or even just cass-operator:
```
➜  k8ssandra git:(disable_cassandra) ✗ helm install demo charts/k8ssandra --create-namespace -n k8ssandra-1 --set cassandra.enabled=false --set kube-prometheus-stack.enabled=false --set reaper.enabled=false --set stargate.enabled=false --set reaper-operator.enabled=false
W0401 10:26:24.355313   59581 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0401 10:26:24.754009   59581 warnings.go:70] apiextensions.k8s.io/v1beta1 …
```
=> Add the ability to disable creation of Cassandra cluster

CHANGELOG.md, charts/k8ssandra/templates/cassandra/cassdc.yaml, tests/unit/template_cassdc_test.go, tests/unit/utils/cassdc/volumes.go
Adds a new volume named `podinfo` which creates a file with the pod's labels. I have added a volume mount for the new `podinfo` volume in the `cassandra` container primarily for manual testing and verification. We really only need it for the `medusa-restore` container though.
The file that is created is /etc/podinfo/labels and looks like this:
```
app.kubernetes.io/managed-by="cass-operator"
cassandra.datastax.com/cluster="test"
cassandra.datastax.com/datacenter="dc1"
cassandra.datastax.com/node-state="Started"
cassandra.datastax.com/rack="default"
cassandra.datastax.com/seed-node="true"
controller-revision-hash="test-dc1-default-sts-6f859cfd9"
statefulset.kubernetes.io/pod-name="test-dc1-default-sts-0"
```
Fixes #613
**Checklist**
=> add volume with pod labels

CHANGELOG.md, pkg/cleaner/cleaner.go, pkg/cleaner/cleaner_test.go
Updates the cleaner job to block until CassandraDatacenters installed in the release are gone.
Fixes #623
**Checklist**
=> [#623] wait for CassandraDatacenters to be gone before exiting

CHANGELOG.md, charts/k8ssandra/templates/cassandra/cassdc.yaml, charts/k8ssandra/templates/medusa/medusa-config.yaml, charts/k8ssandra/values.yaml, tests/unit/template_cassdc_test.go
Removes the Jolokia integration. Jolokia is no longer needed since Medusa now supports management-api for creating snapshots. This PR allows us to get rid of the `get-jolokia` init container as well as remove the jolokia agent from Cassandra.
The Changes in Medusa are in master but not yet released. This PR updates the default Medusa image to one build from the master branch in Medusa. As soon we have a new release of Medusa we can update the default image again. That shouldn't hold up this PR though.
Fixes #533
**Checklist**
=> remove jolokia integration

.github/workflows/integration-tests.yaml
I already submitted a PR for this, but it looks like the behavior was not completely fixed. I still see integration tests running on PRs that do not include code changes.
=> We should not run integration tests on PRs that do not involve code changes

.github/workflows/integration-tests.yaml, CHANGELOG-1.2.md, charts/k8ssandra/templates/cassandra/cassdc.yaml, charts/k8ssandra/templates/medusa/medusa-config.yaml, charts/k8ssandra/values.yaml, tests/integration/charts/cluster_with_medusa_local.yaml, tests/integration/charts/one_node_cluster_with_medusa_local.yaml, tests/integration/integration_suite_test.go, tests/unit/template_cassdc_test.go, tests/unit/template_medusa_config_test.go
Adds the ability to create additional PersistentVolumes to Cassandra pods for the medusa's local storage option.
Fixes #560 
**Checklist**
=> Enable Medusa local storage option to store the backups

.github/workflows/release-next.yaml
Since Helm v3+ supports prereleases natively and hides them unless the `--devel` flag is used, we will stop maintaining the  `next` helm repo and publish prereleases to the `stable` repo.
Installing a prerelease requires then to use the `--devel` flag.
Fixes #599
**Checklist**
=> Remove the next repo and publish prereleases to the stable one

CHANGELOG-1.2.md, charts/k8ssandra/values.yaml
Upgrade Medusa to 0.10.1 which contains a fix for using Minio with the default region and also removes the protocol version enforcement which created a bug in K8ssandra when taking backups after a restore.
Fixes #678 
Fixes #705 
**Checklist**
=> Upgrade to Medusa 0.10.1 fixing failed backups after a restore

Makefile
Changes the download path for setup-envtest.sh, existing path no longer exists.
Fixes #713 
**Checklist**
=> Hotfix, use setup-envtest.sh from controller-runtime 0.8.3

CHANGELOG-1.2.md, charts/k8ssandra/templates/stargate/stargate.yaml, charts/k8ssandra/values.yaml, tests/unit/template_stargate_test.go
* Modifies Stargate init container to wait not for one, but for all nodes in datacenter 0.
* Modifies the initial delay for Stargate probes
Fixes #654
**Checklist**
=> Reduce initial delay of Stargate readiness probe

.github/workflows/publish-website.yaml, .github/workflows/regenerate-reference-docs.yaml
**What this PR does**: Enables the regeneration of chart reference docs
Fixes #807
**Checklist**
=> Fixes #807 - Triggers docs regeneration on pushes to main

CHANGELOG-1.2.md, charts/k8ssandra/templates/reaper/reaper.yaml, charts/k8ssandra/values.yaml, go.mod, go.sum, tests/unit/template_reaper_test.go
Adds support for additional autoscheduling properties. Requires updated reaper-operator version.
Fixes #224
**Checklist**
=> Allow setting additional autoscheduling properties, fixes #224

.github/workflows/publish-website.yaml, docs/package-lock.json, docs/package.json, scripts/README.md, scripts/install-npm-tools.sh
Corrects the failing doc builds by adding in the missing peer dependency of the newer libraries being used.
This also removes the intermediate `install-npm-tools` script in favor of declaration within the package.json file for the docs module.
I tested the workflow in my fork and you can see [here](https://github.com/jdonenine/k8ssandra/runs/2794902349?check_suite_focus=true) that it built successfully.  The deploy fails because it was in my fork without the required secrets.
Fixes #873  
**Checklist**
=> Fix doc builds [K8SSAND-566]

.github/workflows/dependency-upgrade.yaml
The dependency upgrade check workflow is a scheduled one, which can't be manually triggered.
This commit adds workflow_dispatch as trigger for the workflow, which allows manual start.
=> Allow manual triggering of dependency check workflow

.github/workflows/dependency-upgrade.yaml
Using the repository default token will not trigger CI as intended by GH.
Switching to a Personal Access Token will trigger CI on PR creation by the dependency upgrade workflow.
=> Use personal access token to trigger CI

CHANGELOG-1.3.md, charts/k8ssandra/values.yaml
=> Upgrade Reaper dependency 2.2.2 -> 2.2.5

tests/integration/steps/integration_steps.go
Fixes failing upgrade test by giving some time for cass-operator to update the cassdc object in case of an upgrade. Since this state change is optional (sometimes the source/target versions are too close for them to trigger an update), the condition is not failing the whole test if it's not fulfilled.
**Checklist**
=> Improve post-upgrade checks

CHANGELOG-1.3.md, charts/k8ssandra/templates/_helpers.tpl, charts/k8ssandra/templates/cassandra/cassdc.yaml, go.mod, go.sum, tests/unit/template_cassdc_test.go, tests/unit/template_function_test.go, tests/unit/utils/helm/helm.go
Detection of IEC formatted (base 2) values used instead of SI (base 10) for C* `heap.size` and `heap.newGenSize` at both the c* cluster and dc levels.  E.g. no longer support 1MiB, but would need to be 1M.
Fixes #701 
**Checklist**
=> Detect IEC formatted c* heap.size and heap.newGenSize

CHANGELOG-1.3.md, charts/k8ssandra/templates/_helpers.tpl, tests/unit/template_medusa_user_secret_test.go, tests/unit/template_reaper_user_secret_test.go, tests/unit/template_stargate_user_secret_test.go, tests/unit/template_superuser_secret_test.go
Prevents cluster deployment from failing if the Cassandra cluster name contains underscores or spaces, which are not allowed for naming Kubernetes objects.
Fixes #870
**Checklist**
=> Hot replace disallowed characters in generated secret names [K8SSAND-563]

.github/workflows/integration-tests-release.yaml, .github/workflows/k8s_matrix_test.yaml
Adds a GHA workflow that is scheduled weekly to test various versions of Kubernetes.
This workflow will trigger the integration tests workflow using a workflow_dispatch event and sending the k8s version to use as input parameter.
Fixes #919
**Checklist**
=> Add a scheduled workflow to run integration tests on a matrix of k8s versions

CHANGELOG-1.3.md, charts/k8ssandra/templates/prometheus/service_monitor.yaml, charts/k8ssandra/templates/stargate/service_monitor.yaml, charts/k8ssandra/values.yaml, tests/unit/template_stargate_service_monitor_test.go
Allows to configure the namespace in which the service monitors are deployed.
Fixes #844
**Checklist**
=> Make the service monitors namespace configurable

.github/workflows/integration-tests-release.yaml, tests/unit/template_stargate_test.go
Makes Stargate unit tests not dependent on a specific Stargate version.
Also applies a workaround to some kernel related issues with Kind, and upgrades Kind to v0.11.1
**Checklist**
=> Make stargate unit tests not dependent on specific versions

CHANGELOG-1.3.md, charts/k8ssandra/Chart.yaml, charts/k8ssandra/values.yaml, charts/reaper-operator/Chart.yaml, charts/reaper-operator/values.yaml
Upgrade to reaper-operator 0.3.3 and Reaper 2.3.0, which use an init-container to initialize the schema. This will make schema migration safer as they will not be subject to probes.
**Checklist**
=> Upgrade to reaper-operator 0.3.3 and Reaper 2.3.0

charts/k8ssandra/values.yaml
=> Upgrade Reaper dependency 2.3.0 -> 2.3.1

CHANGELOG-1.3.md, charts/k8ssandra/templates/cassandra/cassdc.yaml, tests/unit/template_cassdc_test.go, tests/unit/testdata/init-containers-values.yaml
Adds experimental support for custom init containers in Cassandra pods. Here is an example overrides file to demonstrate:
```yaml
cassandra:
initContainers:
- name: foo
image: docker.io/foo:latest
- name: bar
image: docker.io/bar:latest
```
These containers will be added after all of the init containers that k8ssandra adds.
Fixes #952 
**Checklist**
=> experimental support for init containers in cassandra pod

.github/workflows/k8s_matrix_test.yaml
Adds v1.21.1 back to the version matrix for k8s version testing.
Originally when the matrix was added we saw problems with kind starting a cluster running version 1.21.1 - both locally and within CI.  That now seems to be working.
You can see the run in my fork here:  https://github.com/jdonenine/k8ssandra/actions/runs/1031228580
Fixes #923  
**Checklist**
=> Add v1.21.1 to matrix

docs/content/en/install/doks/doks.values.yaml
Briefly discussed with Michael B, newGenSize shouldn’t equal heap size. Part of addressing issue #866.
**Checklist**
=> NewGenSize: 5G instead of 31G per Michael

charts/k8ssandra/templates/cassandra/cassdc.yaml, charts/k8ssandra/templates/cleaner/batch_job.yaml, charts/k8ssandra/templates/cleaner/service_account.yaml, charts/k8ssandra/templates/crd/batch_job.yaml, charts/k8ssandra/templates/crd/service_account.yaml, charts/k8ssandra/templates/reaper/reaper.yaml, charts/k8ssandra/templates/stargate/stargate.yaml, charts/k8ssandra/values.yaml
Makes the service account to use configurable. It does not however allow you to configure the service account. This just give you the ability to point to the one you want to use.
I did not update the changelog for this since this PR really should have been part of #901.
Ideally, for the cleaner and crd upgrader, I would have liked to use the `k8ssandra-common.serviceAccount` template. It makes the service account name as well as image pull secrets available. It would require some refactoring to be able to safely use it for them though. The template assumes the scope of `.Values`. This would need to change and certainly beyond the scope of 1.3.0 at this point.
Fixes #983, #984, #985
**Checklist**
=> make service accounts configurable for reaper, cleaner, and crd upgrader

CHANGELOG-1.4.md, charts/k8ssandra/templates/_helpers.tpl, tests/integration/steps/integration_steps.go
Changes the `k8ssandra.default_num_tokens` template to check if it is an upgrade. If it is an upgrade and `num_tokens` is not set then we make sure that `num_tokens` has the correct default based on the current version of Cassandra. So if the upgrade goes from 3.11.10 to 4.0 for example, then `num_tokens` will remain set to 256.
Fixes #1029, #1020
**Checklist**
=> do not change num_tokens when upgrading

CHANGELOG-1.4.md, charts/k8ssandra/values.yaml, tests/integration/charts/cluster_full_stack.yaml, tests/integration/charts/cluster_with_medusa_azure_blobs.yaml, tests/integration/charts/cluster_with_medusa_minio.yaml, tests/integration/charts/cluster_with_medusa_minio_upgraded.yaml, tests/integration/charts/cluster_with_medusa_s3.yaml
Upgrades Medusa to 0.11.1 and configure the integration tests to partially rely on the provider's cli for backup/restore, in order to reproduce the issue.
Fixes #1066
**Checklist**
=> Fix Azure backups with an update to Medusa 0.11.1

docs/content/en/quickstarts/site-reliability-engineer/_index.md
Hi, I found a missing shortcut link for [Reaper](https://docs.k8ssandra.io/quickstarts/site-reliability-engineer/#reaper) on the outline part when I read document: https://docs.k8ssandra.io/quickstarts/site-reliability-engineer. By the way, it's well documented and good practice for me. Thanks.
**Which issue(s) this PR fixes**:  
N/A
**Checklist**
=> ShortCut link fixing for doc

CHANGELOG-1.4.md, charts/k8ssandra/templates/prometheus/service_monitor.yaml, tests/integration/integration_suite_test.go, tests/integration/steps/integration_steps.go, tests/integration/steps/monitoring_steps.go
Fix "out of order" metrics being scraped by Prometheus. A new `kind` label is introduced to distinguish histograms and meters being sent by MCAC for the current same set of labels.
I've added an integration test which failed without the fix: https://github.com/adejanovski/k8ssandra/runs/3533754080?check_suite_focus=true
Fixes #969 
**Checklist**
=> Fix relabelings to avoid out of order metrics error

charts/cass-operator/values.yaml, charts/k8ssandra-common/templates/_helpers.tpl, charts/k8ssandra/templates/cassandra/cassdc.yaml, tests/unit/template_cassdc_test.go, tests/unit/utils/cassdc/containers.go
Temporarily relax the default `securityContext` for containers to resolve issue reported with c* image failing `mkdir` as root in GKE.
Fixes #1094 
[k8ssand-875](https://k8ssandra.atlassian.net/browse/K8SSAND-875)
**Checklist**
=> Temp relax read-only for containers

charts/cass-operator/Chart.yaml, charts/cass-operator/templates/configmap.yaml, charts/cass-operator/templates/deployment.yaml, charts/cass-operator/values.yaml, charts/k8ssandra-operator/Chart.yaml, charts/k8ssandra/Chart.yaml, charts/k8ssandra/values.yaml
…gmap
This PR addresses the forum discussion [here](https://forum.k8ssandra.io/t/k8ssandra-operator-and-helm-charts/332/9). It adds the cass-operator dependency to the k8ssandra-operator chart so that the latter can be used on its own.
I am not creating a separate issue for this. It can be logged under #1080.
Fixes #1080
**Checklist**
=> k8ssandra-operator chart updates

CHANGELOG-1.4.md, charts/k8ssandra/templates/cassandra/cassdc.yaml, charts/k8ssandra/values.yaml, tests/unit/template_cassdc_test.go
Introduces the ability to create filters for Cassandra metrics in Helm values files. The default filters fix the issues observed when 300+ tables were created in the Cassandra cluster, overwhelming collectd and/or scraping, resulting into all metrics being dropped.
They filter all table level metrics that are not used in our default dashboards.
Fixes #1092
**Checklist**
=> Apply MCAC filters for table level metrics

CHANGELOG-1.4.md, charts/k8ssandra/values.yaml
=> Upgrade Reaper dependency 2.3.1 -> 3.0.0

CHANGELOG-1.4.md, charts/k8ssandra/Chart.yaml, charts/k8ssandra/README.md, charts/reaper-operator/Chart.yaml, charts/reaper-operator/crds/reaper.yaml, charts/reaper-operator/templates/leader_election_role.yaml, charts/reaper-operator/templates/role.yaml, charts/reaper-operator/values.yaml
* Upgrade reaper-operator manifests to align with latest config/ in main repo. (operator-sdk 1.6.1/controller-runtime 0.9.2).
* Brings CRD API versions up to v1 from v1beta1, making compatible with k8s 1.22.
* Add additional RBAC configs required by leader election in more recent operator-sdk versions.
#1150.
**Checklist**
- [ NA ] Automated Tests added/updated
- [ NA ] Documentation added/updated
- [ NA ] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)
=> Reaper operator updates for operator sdk 1.6.1 [K8SSAND-1009]

.github/workflows/integration-tests-release.yaml, CHANGELOG-1.4.md, charts/k8ssandra/templates/cassandra/cassdc.yaml, charts/k8ssandra/templates/stargate/stargate.yaml, charts/k8ssandra/values.yaml, tests/integration/charts/cluster_with_custom_config.yaml, tests/integration/integration_suite_test.go, tests/integration/testdata/cassandra-config.yaml, tests/unit/template_cassdc_test.go, tests/unit/template_stargate_test.go
Adds a `cassandraYamlConfigMap` property for Cassandra and Stargate. The property specifies a ConfigMap that contains a custom cassandra.yaml. The custom cassandra.yaml is merged with the base config.
As noted in the comments in values.yaml, there are a number of properties that should not be specified in the custom cassandra.yaml. Some properties, like those that require setting up volumes and mounts need to be handled separately. Others are generated elsehwere in the the cassdc.yaml template.
Fixes #1023, #1166, #1169, #1177
**Checklist**
=> Custom cassandra.yaml for Cassandra and Stargate [K8SSAND-793][K8SSAND-1036][K8SSAND-1038][K8SSAND-1044]

CHANGELOG-1.4.md, charts/k8ssandra/values.yaml, tests/integration/integration_suite_test.go, tests/integration/steps/medusa_steps.go
Adds an integration test to check that the `./last-restore` file is properly created after a restore to avoid restoring a backup on subsequent restarts of a Cassandra pod.
Fixes #1112
**Checklist**
=> Add integration tests to verify proper restore completion [K8SSAND-921]

charts/k8ssandra/templates/cassandra/cassdc.yaml
This is a follow up to #1180. An empty volumeMounts fails on k8s versions earlier than 1.21 with this error:
`Error: CassandraDatacenter.cassandra.datastax.com "dc1" is invalid: spec.podTemplateSpec.spec.containers.volumeMounts: Invalid value: "null": spec.podTemplateSpec.spec.containers.volumeMounts in body must be of type array: null`
This commit makes sure we avoid an empty volumeMounts property.
**Checklist**
=> don't declare an empty volumeMounts

charts/k8ssandra/templates/reaper/reaper.yaml
On k8s versions < 1.21 creation of the Reaper object can fail with this:
`Error: Reaper.reaper.cassandra-reaper.io "k8ssandra-reaper" is invalid: spec.schemaInitContainerConfig: Invalid value: "null": spec.schemaInitContainerConfig in body must be of type object: null`
This commit fixes it by not creating empty containers.
**Checklist**
=> don't create empty (i.e., null) containers in Reaper object

CHANGELOG-1.4.md, charts/k8ssandra/templates/cassandra/cassdc.yaml, charts/k8ssandra/values.yaml
Reverts the addition of pod level `securityContext` on the Cassandra pods.
These prevented Cassandra data dir creation due to improper rights on `/var/lib/cassandra`.
Fixes #1206
**Checklist**
=> Remove pod level SecurityContext to fix permissions issue [K8SSAND-1071]

CHANGELOG-1.4.md, CHANGELOG-1.5.md, charts/k8ssandra/templates/_helpers.tpl, tests/unit/template_cassdc_test.go
Adds similar clusterName cleanup to our Helm templates as we have in cass-operator. This is because some of the resources created by k8ssandra helm charts are not using cass-operator's logic.
Allows "broken" clusterNames which do not conform to DNS rules.
Fixes #1090
**Checklist**
=> Add clusterName cleanup similar to cass-operator to k8ssandra [K8SSAND-873]

charts/k8ssandra-operator/templates/role.yaml
Adds RBAC permissions to the k8ssandra-operator role. This gives the controller permissions to reconcile Prometheus ServiceMonitors which is required by the telemetry functionality implemented under #234, #236.
Fixes #1224 
**Checklist**
=> Add prometheus related permissions to k8ssandra-operator role.

charts/cass-operator/Chart.yaml, charts/cass-operator/templates/deployment.yaml, charts/cass-operator/templates/role.yaml, charts/cass-operator/templates/rolebinding.yaml, charts/cass-operator/values.yaml, charts/k8ssandra-operator/Chart.yaml, charts/k8ssandra-operator/crds/k8ssandra.io_k8ssandraclusters.yaml, charts/k8ssandra-operator/crds/reaper.k8sandra.io_reapers.yaml, charts/k8ssandra-operator/crds/replication.k8ssandra.io_replicatedsecrets.yaml, charts/k8ssandra-operator/crds/stargate.k8ssandra.io_stargates.yaml, charts/k8ssandra-operator/templates/clusterrole.yaml, charts/k8ssandra-operator/templates/clusterrolebinding.yaml, charts/k8ssandra-operator/templates/deployment.yaml, charts/k8ssandra-operator/templates/role.yaml, charts/k8ssandra-operator/templates/rolebinding.yaml, charts/k8ssandra-operator/values.yaml, charts/k8ssandra/Chart.yaml
* Add/update CRDs
* Add support for cluster-scoped deployment
* Fix naming
* Update RBAC
* `clusterScoped` chart property is now global in both k8ssandra-operator and in cass-operator charts
By making `clusterScoped` global it only needs to be set once vs setting it separately for both charts, e.g.,
`helm install test ./charts/k8ssandra-operator --set "global.clusterScoped=true"`
whereas without the global variable you would instead have to do,
`helm install ./charts/k8ssandra-operator --set "clusterScoped=true,cass-operator.clusterScoped=true"`
Making `clusterScoped` global makes it easier for users without introducing a lot additional complexity in the chart templates.
Fixes #1235
**Checklist**
=> several k8ssandra-operator chart updates [K8SSAND-1128][K8SSAND-1129]

docs/assets/scss/_colab_styles.scss, docs/layouts/partials/navbar-version-selector.html, docs/layouts/partials/navbar.html
Makes the new `Versions` dropdown available on the mobile resolution version of the menu.
This will need to be cherry picked to `docs` and `docs-v1` as well.
N/A
**Checklist**
=> Fix versions dropdown on mobile resolutions

.github/workflows/dependency-upgrade.yaml, charts/k8ssandra/Chart.yaml
Updates the dependency upgrade GHA workflow to upgrade the following operators:
- k8ssandra-operator
- cass-operator
- reaper-operator
- medusa-operator
Sample generated PRs can be seen [here](https://github.com/adejanovski/k8ssandra/pulls).
Fixes #1304
Fixes #1305
**Checklist**
=> Add operators in the dep upgrade workflow

charts/cass-operator/Chart.yaml, charts/cass-operator/values.yaml, charts/k8ssandra-operator/Chart.yaml, charts/k8ssandra/Chart.yaml
=> Upgrade cass-operator dependency 1.10.0 -> 1.10.1

docs/README.md
Steps to publish doc updates to live external site. Without new tag push, merged updates are pushed only to docs-staging*.
**Checklist**
=> Add doc tagging example

CHANGELOG-1.5.md, charts/k8ssandra/values.yaml
=> Upgrade Reaper dependency 3.0.0 -> 3.1.1

CHANGELOG-1.5.md, charts/k8ssandra/values.yaml
=> Upgrade Stargate dependency 1.0.44 -> 1.0.50

.github/workflows/integration-tests-release.yaml
The build and release workflow failed on the last merged to main (see [here](https://github.com/k8ssandra/k8ssandra/runs/5661657938?check_suite_focus=true)) with this error:
```
Error: On 2022-04-05, the default branch will be renamed from "master" to "main". Your action is currently pinned to "@master". Even though GitHub creates redirects for renamed branches, testing found that this rename breaks existing GitHub Actions workflows that are pinned to the old branch name.
We strongly advise updating your GitHub Action YAML from:
uses: 'google-github-actions/setup-gcloud@master'
to:
uses: 'google-github-actions/setup-gcloud@v0'
```
=> update setup-gclouds-action action

CHANGELOG-1.5.md, charts/k8ssandra/templates/_helpers.tpl, charts/k8ssandra/templates/cassandra/cassdc.yaml, charts/k8ssandra/values.yaml, tests/integration/charts/cluster_full_stack.yaml, tests/integration/charts/cluster_with_medusa_minio_upgraded.yaml, tests/integration/charts/cluster_with_reaper.yaml, tests/integration/charts/cluster_with_reaper_upgraded.yaml, tests/integration/steps/integration_steps.go, tests/unit/template_4x_features_test.go, tests/unit/template_cassdc_test.go
Fixes GC settings for Cassandra 4.0 which were not applied correctly as they are supposed to go in jvm11-server.options and jvm-server.options, but were only going in the latter.
I also introduced the possibility to use ZGC with Cassandra 4.0 as it's available with JDK11 and cass-config-definitions support it.
Fixes #1269
**Checklist**
=> Fix gc properties 4.0

CHANGELOG-1.5.md, charts/k8ssandra/values.yaml
=> Upgrade Medusa dependency 0.12.1 -> 0.12.2

CHANGELOG-1.5.md, charts/cass-operator/Chart.yaml, charts/cass-operator/values.yaml, charts/k8ssandra-operator/Chart.yaml, charts/k8ssandra/Chart.yaml
=> Upgrade cass-operator dependency 1.10.1 -> 1.10.3

docs/content/en/install/local/multi-cluster-helm/_index.md
howdy, John&Mike? :D I bumped into some minor typos when checking the docs. Hopefully, I am targeting the correct branch, because there are also those `docs-v2-vx.y.z` branches.
Fixes some typos & [this](https://docs-v2.k8ssandra.io/install/local/multi-cluster-helm/#install-k8ssandra-operator-in-the-data-planes)
no issue created (too minor)
**Checklist**
=> Fix typos in multi-cluster-helm tutorial

CHANGELOG-1.6.md, charts/cass-operator/Chart.yaml, charts/cass-operator/values.yaml, charts/k8ssandra-operator/Chart.yaml, charts/k8ssandra/Chart.yaml
=> Upgrade cass-operator dependency 1.10.3 -> 1.11.0

charts/cass-operator/Chart.yaml, charts/k8ssandra-common/Chart.yaml, charts/k8ssandra-common/README.md, charts/k8ssandra-operator/Chart.yaml, charts/k8ssandra-operator/templates/clusterrole.yaml, charts/k8ssandra/Chart.yaml, charts/medusa-operator/Chart.yaml, charts/reaper-operator/Chart.yaml
Updates the ClusterRole template for the K8ssandra-operator helm chart, to include the new Medusa CRDs introduced in v1.1.
Fixes #1417
**Checklist**
=> Update clusterrole template for k8ssandra-operator v1.1

CHANGELOG-1.5.md, charts/cass-operator/Chart.yaml, charts/cass-operator/values.yaml, charts/k8ssandra-common/Chart.yaml, charts/k8ssandra-common/README.md, charts/k8ssandra-operator/Chart.yaml, charts/k8ssandra/Chart.yaml, charts/medusa-operator/Chart.yaml, charts/reaper-operator/Chart.yaml
Upgrades cass-operator to 1.10.4 on the 1.5 release branch.
This will allow releasing 1.10.4 to our Helm repo.
**Checklist**
=> Upgrade cass operator 1.10.4 1.5

CHANGELOG-1.6.md, charts/k8ssandra/values.yaml
=> Upgrade Reaper dependency 3.1.1 -> 3.2.0

CHANGELOG-1.6.md, charts/cass-operator/Chart.yaml, charts/cass-operator/values.yaml, charts/k8ssandra-operator/Chart.yaml, charts/k8ssandra/Chart.yaml
=> Upgrade cass-operator dependency 1.11.0 -> 1.12.0

CHANGELOG-1.6.md, charts/k8ssandra/values.yaml
=> Upgrade Stargate dependency 1.0.52 -> 1.0.61

pkg/crds/upgrade.go, pkg/crds/upgrade_test.go, pkg/helmutil/fetch.go
Uses `k8ssandra` as default chart name if it isn't provided.
This should fix the K8ssandra v1.x upgrade issues as a new `chartName` argument was introduced to support K8ssandra-operator, but no default value was defined to handle the former invocations made by K8ssandra v1.
Fixes #1478 
**Checklist**
=> Fix CRD upgrader breakage for the k8ssandra chart

CHANGELOG-1.6.md, charts/k8ssandra/values.yaml
=> Upgrade Stargate dependency 1.0.61 -> 1.0.63

charts/k8ssandra-operator/Chart.yaml, charts/k8ssandra-operator/values.yaml
=> Upgrade k8ssandra-operator dependency 1.2.0 -> 1.2.1

CHANGELOG-1.6.md, charts/cass-operator/Chart.yaml, charts/cass-operator/values.yaml, charts/k8ssandra-operator/Chart.yaml, charts/k8ssandra/Chart.yaml
=> Upgrade cass-operator dependency 1.12.0 -> 1.13.0

.github/workflows/update-crd-reference.yaml, docs/config/crdoc-templates/_index_cass_operator_crds.md, docs/config/crdoc-templates/_index_k8ssandra_operator_crds.md, docs/config/crdoc-templates/_index_releases.md, docs/config/crdoc-templates/cassdc.tmpl, docs/config/crdoc-templates/k8c.tmpl
Adds a GHA workflow which:
- triggers every day at 1am UTC
- checks out K8ssandra-operator
- checks out cass-operator
- checks out K8ssandra@docs-v2
- Generates the CRD documentation for all release branches and the main branch
- Sends a PR against K8ssandra@docs-v2 if the CRD ref content has changed with the updated content
The CRD reference was reorganized as can be seen [here](https://docs-staging-v2.k8ssandra.io/reference/crd/).
Fixes #1459 
**Checklist**
=> Add a GHA workflow which pushes PRs for CRD reference documentation updates

charts/cass-operator/Chart.yaml, charts/cass-operator/templates/_helpers.tpl, charts/cass-operator/templates/configmap.yaml, charts/cass-operator/templates/deployment.yaml, charts/cass-operator/templates/validatingwebhookconfiguration.yaml, charts/cass-operator/templates/webhook-service.yaml, charts/cass-operator/values.yaml, charts/k8ssandra-operator/Chart.yaml
…in k8ssandra-operator. This changes name of multiple resources and some labels, causing cass-operator to redeploy itself
cass-operator Helm charts worked fine when deployed independently (like designed), however when used as a dependency in k8ssandra-operator, the k8ssandra-operator renamed certain resources to start conflicting with k8ssandra-operator resources.
This PR modifies the naming in cass-operator to work when k8ssandra-operator renames them..
Fixes k8ssandra/k8ssandra-operator#769
**Checklist**
=> Fix naming of cass-operator charts to work when used as a dependency

CHANGELOG-1.5.md, charts/k8ssandra/values.yaml
=> Upgrade Stargate dependency 1.0.63 -> 1.0.68

docs/content/en/install/local/multi-cluster-helm/_index.md, docs/content/en/install/local/multi-cluster-kustomize/_index.md, docs/content/en/install/local/single-cluster-helm/_index.md, docs/content/en/install/local/single-cluster-kustomize/_index.md
The installation quickstart docs contain erroneous commands and refer to old versions of k8ssandra-operator.
This PR fixes those issues.
No issue
**Checklist**
=> Fix installation docs

charts/cass-operator/Chart.yaml, charts/k8ssandra-common/Chart.yaml, charts/k8ssandra-common/templates/_helpers.tpl, charts/k8ssandra-operator/Chart.yaml, charts/k8ssandra-operator/templates/serviceaccount-token.yaml, charts/k8ssandra/Chart.yaml, charts/medusa-operator/Chart.yaml, charts/reaper-operator/Chart.yaml
Kubernetes 1.24 stopped creating secrets for service account tokens by default, relying instead on the TokenRequest API.
This is something we've dealt with in our Kustomization but not on Helm installs for k8ssandra-operator.
This PR adds a secret creation for the service account if the kube version is 1.24+ and references the secret in the service account manifest.
Fixes k8ssandra/k8ssandra-operator#793
**Checklist**
=> Fix service account token generation for k8s 1.24+

charts/k8ssandra-operator/Chart.yaml, charts/k8ssandra-operator/crds/k8ssandra-operator-crds.yaml, charts/k8ssandra-operator/values.yaml
=> Upgrade k8ssandra-operator dependency 1.4.0 -> 1.4.1

CHANGELOG-1.6.md, charts/cass-operator/README.md, charts/cass-operator/templates/deployment.yaml, charts/cass-operator/values.yaml
Adds nodeSelector and tolerations parameters support to cass-operator helm chart
Fixes #1612 
**Checklist**
I saw message this repository is deprecated, however, looks like cass-operator is still being released from this repo.
Looks like helm-docs was not executed for a while. I excluded everything but cass-operator helm chart docs update, let me know if I should run it for all charts.
=> Added nodeSelector and tolerations to cass-operator helm chart

charts/cass-operator/Chart.yaml, charts/cass-operator/values.yaml
Use UBI8 base image for the cass-config-builder instead of UBI7 (adds ARM64 support)
**Checklist**
=> Update cass-operator chart to use UBI8 image of the cass-config-builder

charts/cass-operator/Chart.yaml, charts/cass-operator/templates/rolebinding.yaml
Fix clusterrolebinding creation.
After PR https://github.com/k8ssandra/k8ssandra/pull/1657, the ClusterRole is now created unconditionally but its related ClusterRoleBinding is still created only if .Values.global.clusterScoped is true
**Checklist**
=> Fix: Create Clusterrolebinding in cass-operator chart in any case

charts/cass-operator/Chart.yaml, charts/cass-operator/templates/configmap.yaml, charts/cass-operator/values.yaml
```
image_config.yaml: |
apiVersion: config.k8ssandra.io/v1beta1
kind: ImageConfig
images:
system-logger: cr.k8ssandra.io/k8ssandra/system-logger:v1.22.3
config-builder: cr.dtsx.io/datastax/cass-config-builder:1.0-ubi8
k8ssandra-client: cr.k8ssandra.io/k8ssandra/k8ssandra-client:v0.5.0
imagePullPolicy: IfNotPresent
defaults:
cassandra:
repository: cr.k8ssandra.io/k8ssandra/cass-management-api
suffix: -ubi
dse:
repository: cr.dtsx.io/datastax/dse-mgmtapi-6_8
suffix: -ubi8
hcd:
repository: cr.dtsx.io/datastax/hcd
suffix: -ubi
```
Fixes https://github.com/k8ssandra/cass-operator/issues/715
**Checklist**
=> Move imageConfig defaults settings to values.yaml

charts/cass-operator/Chart.yaml, charts/cass-operator/templates/configmap.yaml, charts/cass-operator/templates/deployment.yaml, charts/cass-operator/templates/leader_election_role.yaml, charts/cass-operator/templates/leader_election_role_binding.yaml, charts/cass-operator/templates/role.yaml, charts/cass-operator/templates/rolebinding.yaml, charts/cass-operator/templates/validatingwebhookconfiguration.yaml, charts/cass-operator/templates/webhook-service.yaml, charts/cass-operator/values.yaml, charts/k8ssandra-common/Chart.yaml, charts/k8ssandra-common/templates/_helpers.tpl, charts/k8ssandra/Chart.yaml, charts/medusa-operator/Chart.yaml, charts/reaper-operator/Chart.yaml
Updates k8ssandra-common to apply commonLabels (local and global ones) to all resources using the labels helper function. Also duplicates the labels logic for annotations.
Makes cass-operator apply both labels and annotations to all the rendered templates.
**Checklist**
=> Add common annotations and map both annotations and labels to all resources

charts/cass-operator/Chart.yaml, charts/cass-operator/templates/role.yaml, charts/cass-operator/templates/rolebinding.yaml, charts/cass-operator/values.yaml
Allows blocking render of clusterScoped resources for cass-operator chart.
**Checklist**
=> If global.clusterScopedResources is set to false, do not render any

charts/cass-operator/Chart.yaml, charts/cass-operator/templates/validatingwebhookconfiguration.yaml
This pull request includes a version update for the `cass-operator` chart and introduces a conditional block for cluster-scoped resources in the ValidatingWebhookConfiguration template. Below are the key changes:
* [`charts/cass-operator/Chart.yaml`](diffhunk://#diff-4a567ecacde4b3189d86c51760c52e944b7f9d846fe7e770df66dfd7fd473970L6-R6): Updated the chart version from `0.59.0` to `0.59.1`.
* [`charts/cass-operator/templates/validatingwebhookconfiguration.yaml`](diffhunk://#diff-36fde6970f5b5c04df1357fa713151ca8e85b24e64f5dcf2dced0d12f0c5d8bfR10): Added a conditional block to include `ValidatingWebhookConfiguration` only if `.Values.global.clusterScopedResources` is set. This ensures the configuration is applied conditionally based on the cluster-scoped resource …
=> Disable the creation of the validating webhook when cluster level resources are disabled
